### ISSUE TITLE
WPS dataInput changes

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1010]
- [x] a datainput is used to access to a table stored in a RDBMS,
- [x] remove the tag geocatalog,
- [x] replace the method is spatial with the tableTypes meta information that could be set with the constants GEOMETRY, RASTER,
- [x] remove the file extension (A file must be imported or linked with the database).

**Comment by SPalominos** [comment]
Issue solved in the branch dev/wps.
