### ISSUE TITLE
OrbisGIS cannot be launched from outside its own dir.

### ISSUE THREAD

**Issue by sbigaret** [orbisgis/orbisgis#1015]
When outside the OrbisGIS directory:

`java -jar orbisgis.jar`  starts... then remain silent and does not display anything (no GUI neither errors in the console)

`/path/to/orbisgis.sh` fails with:
`Error: Unable to access jarfile orbisgis.jar`

**Comment by sbigaret** [comment]
Second case can be resolved by inserting the following line in the orbisgis.sh before invoking java:
`cd $(dirname $0)`

**Comment by sbigaret** [comment]
BTW a shebang would be nice at the beginning of orbisgis.sh (`#! /bin/bash` e.g.)

**Comment by ebocher** [comment]
Thanks a lot.
Patches are welcome ;-)

**Comment by sbigaret** [comment]
Sir Yes Sir!-) pull request #1019 on its way.

**Comment by ebocher** [comment]
Fix thanks to @sbigaret
