### ISSUE TITLE
Request for enhancement: Run selected SQL statements

### ISSUE THREAD

**Issue by sbigaret** [orbisgis/orbisgis#1017]
It would be nice to have a feature «Run selected SQL statements» next to «Run SQL statements»

**Comment by gpetit** [comment]
@sbigaret the job has been done. You can test, using the last release which is here http://jenkins.orbisgis.org/job/orbisgis/lastSuccessfulBuild/artifact/orbisgis-dist/target/orbisgis-bin.zip

Once you selected your SQL line(s) you can click on the dedicated icon (the orange one), or press on ALT+ENTER.

https://github.com/orbisgis/orbisgis/pull/1025

**Comment by ebocher** [comment]
Done
