### ISSUE TITLE
Load scripts depending on the RDBMS

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1048]
Add a method to set if the WPS groovy script could be loaded.
This method must be private and available only internally.

**Comment by SPalominos** [comment]
As the information will be only used by the WPS server which can only access to the metadata, it should be stored in the metadata.

**Comment by ebocher** [comment]
Perfect

**Comment by ebocher** [comment]
Add two constants : postgis and h2gis (not case sensitive)
