### ISSUE TITLE
St_graph function

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1052]
I wanted to used the St_graph function, but I have this message: "Function "ST_GRAPH" not found; SQL statement"

How can I add this function in the last version of OrbisGis ? (I am using: "orbisgis-dist-5.1.0-SNAPSHOT-2016-08-05")

Thanks,

Pierre

**Comment by ebocher** [comment]
oups the last OrbisGIS version loads only the basic functions (org.h2gis.functions.H2GISFunctions.load) .
We must update OrbisGIS to support all extensions as expressed in H2GIS documentation.
Sorry for that.

Example :  http://www.h2gis.org/docs/dev/quickstart/
```sql

CREATE ALIAS IF NOT EXISTS H2GIS_EXTENSION FOR "org.h2gis.ext.H2GISExtension.load";
CALL H2GIS_EXTENSION();
```

@SPalominos 
Could you please update " bundles/core-jdbc/src/main/java/org/orbisgis/corejdbc/DataSourceService.java "

**Comment by pierromond** [comment]
Thank you !

**Comment by nicolas-f** [comment]
ST_Graph is not declared in org.h2gis.ext.H2GISExtension either

**Comment by pierromond** [comment]
Thank you

**Comment by ebocher** [comment]
Ouppppppppppppppppppppppppps

https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java must be updated to add ST_graph function....
I will check

**Comment by ebocher** [comment]
Fixed. It will be available soon with the last H2GIS release.

**Comment by pierromond** [comment]
Thanks !
