### ISSUE TITLE
Process estimated completion

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1063]
The WPS `StatusInfo` answer contains a parameter `EstimatedCompletion` which indicates to the client the estimated process completion date. Currently it is not managed by the server.
It would be useful to be able to send this information to the client and to display it to the user.

**Comment by ebocher** [comment]
Ok.
Did you plan to offer a way to add a "progress monitor" in a groovy script ?
eg.

@process{
progress.start

//Do job

progress.end
}

**Comment by SPalominos** [comment]
Why not, but in the end, each process will be run with a progress monitor. Isn't that enough ? Is there a use to start progress monitors inside a process ?
