### ISSUE TITLE
Scripts Translation

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1088]
Explain in the wiki how to build a script plugin and how to translate the scripts.

**Comment by ebocher** [comment]
Partially done with translation keys.
To close this issue we must find a method to translate internal script. Maybe something based on the same approach as @annotation 

```java

@Process()
def processing() {

literalDataOutput = tr("Process done")
}

@tr(description = ["Process done", ["Process done.","en",
                "Traitement réalisé.","fr"]])

```

**Comment by SPalominos** [comment]
Move into the OrbisWPS repository : orbisgis/orbiswps#6
