### ISSUE TITLE
WPS script preprocess and postprocess method

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1092]
Make possible to add a preprocessing and postprocessing methods to the WPS scripts. The preprocessing one will be executer just before the processing methods execution. The post processing method will be executed after the processing method execution, even if the process has been cancelled.

**Comment by ebocher** [comment]
The preprocessing method will be useful for example to populate an EnumerationInput from a database with the list of table names.

**Comment by SPalominos** [comment]
This issue appears to be more linked to the future process chaining. => issue #1106
