### ISSUE TITLE
Wiki for the WPS process creation

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1097]
Explain in the wiki how to build its own WPS script with the annotation, example ...

**Comment by gpetit** [comment]
We should discuss where we want to put the WPS doc.
If it's limited, the wiki can be a solution. But if it's more detailled, in my opinion, the wiki is not suitable (pblm with the pages name, insertion of images, ...). In this case, doc.orbisgis.org is better.

@ebocher

**Comment by SPalominos** [comment]
Moved into the OrbisWPS repository : orbisgis/orbiswps#7
