### ISSUE TITLE
Start multiple OrbisGIS instances

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1101]
Remove the file instance.lock in the OrbisGIS folder to allow multiple instances of OrbisGIS on different databases.

**Comment by nicolas-f** [comment]
Nope nope. Before removing the lock file, each instance of OrbisGIS must not run on the same workspace and must not share the same temporary files.

A better solution should be to change the architecture of OrbisGIS, in order to have a single java instance but multiple gui with an instance osgi service, but this is a multiple month project.

**Comment by ebocher** [comment]
If you remove the  lock file you can start OrbisGIS with another workspace without any problem. It's an important limitation to not be able to start multiple OrbisGIS instances.
A good start will be to have a schema about the architecture.
@SPalominos

**Comment by nicolas-f** [comment]
You have two java machine instance that shares the same "temporary" jar files (OSGi cache). That is a very problematic situation. 

A less problematic issue is that the two applications share the same log file.

**Comment by SPalominos** [comment]
It seems that we have to reworks a bit the architecture to allow to do that.
Maybe we should discuss how to do it : More than one instance of OrbisGIS or Make OrbisGIS able to handle more than only one database in the same time, more than one TableEditor ...

**Comment by nicolas-f** [comment]
An exemple if we want to manage multiple instance of main panel:

For the SQLConsole here:
https://github.com/orbisgis/orbisgis/blob/master/bundles/sqlconsole/src/main/java/org/orbisgis/sqlconsole/SQLConsole.java

The DataSource is a service reference. However, if we connect to multiple workspace, we will have multiple DataSource service instance. Then, in this case the DataSource should be specified in the attributes of init method https://github.com/orbisgis/orbisgis/blob/master/bundles/sqlconsole/src/main/java/org/orbisgis/sqlconsole/SQLConsole.java#L88

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
