### ISSUE TITLE
Table list not updated in the Geocatalog

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1117]
I'm using the last snapshot version of OG 5.1

In many cases, when I produce a new table, the table does not appear in the Geocatalog, even if I refresh. The table is just shown in the db tree.

I'm not able to reproduce and to understand why this table is concerned, more one another

@ebocher @SPalominos

**Comment by ebocher** [comment]
I'm not able to reproduce this issue.
It seems a lock pb with a corrupted database or thread.

**Comment by ebocher** [comment]
@gpetit  any input

**Comment by SPalominos** [comment]
This bug seems to be not reproducible. We should get the log when the bug happens.
