### ISSUE TITLE
Not able to load an H2GIS local db

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1125]
I created an H2GIS db.

Then I want to load this db in OG. So I create a new workspace and I point the db URI in the configuration panel.
Then when I click on "OK" to launch OG, nothing appears. OG is lost in space (no log in the terminal, ...) ... and I have to kill OG.

@ebocher @SPalominos

**Comment by ebocher** [comment]
Seems a bug with the H2GIS version.
Could you please re-test ?

**Comment by ebocher** [comment]
@gpetit  ?

**Comment by gpetit** [comment]
Seems resolved.

Thanks
