### ISSUE TITLE
No more option to filter objects in the table

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1127]
I'm using the snapshot V5.1

- Load a layer in the map, and open the attributes table,
- with the black arrow, select objets in the map
- in the table, click on "filter selection" --> lines are filtered
- in the map, select another objects
- in the table, click on "delete filter" --> the all table is displayed
- make a right-click to be able to filter once again (on the new selection) --> you don't have any options (except "select cells with the same value")

@ebocher @SPalominos

**Comment by ebocher** [comment]
It's a correct behavior. The filter option is available when the number of selected rows is greater than zero.
