### ISSUE TITLE
Add WPS processes as action in OrbisGIS components.

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1129]
For now, WPS processes can be called by the different OrbisGIS bundles. But it must be changed this way : the bundles should expose points of extension where the WPS client can add action. So it will make easier to manager the action and make it lighter.

**Comment by nicolas-f** [comment]
Yes it is the "white board pattern" of OSGi, it is the best choice for declarative services.

**Comment by SPalominos** [comment]
I'm on it

**Comment by ebocher** [comment]
Excellent
