### ISSUE TITLE
Selection lost on filtered table

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1130]
1. Open a table
2. Select rows
3. Filter rows
4. Disable the filter -> the selection is lost in the table.

**Comment by ebocher** [comment]
@nicolas-f @gpetit 
Do you think its  a normal behaviour ?

**Comment by gpetit** [comment]
No. If possible, when disabling the filter, we should go back to situation n°2

**Comment by SPalominos** [comment]
I'm on it.

**Comment by ebocher** [comment]
works well
