### ISSUE TITLE
Improve Infotool action

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1131]
The idea is to open the corresponding table of the layer when the user tries to obtain info on geometries from the MapEditor.
Geometries are selected on the map.
The table must be filtered to display only the selected geometries.

This issue is under development at https://github.com/ebocher/orbisgis/tree/tableeditor_api

Note : A button has been also added in the table editor to  filter or unfilter the selected rows.

**Comment by ebocher** [comment]
#1140 solves the issue but... Is it possible to solve also this kind of functioning : 

Do not reload the whole table before filtering it because it adds some latency on big table ?

To test 

Run infotool ->  rows are filtered (Ok)
Re run infotool -> the whole table is loaded and the filtered is applied.

**Comment by nicolas-f** [comment]
The model data behind JTable do not change. The only manipulated object is https://docs.oracle.com/javase/7/docs/api/javax/swing/RowSorter.html .

**Comment by gpetit** [comment]
@nicolas-f not clear for me. Is it possible or not to skip the loading of the all table ?

In addition, here the info tool only works if the user draw a rectangle. Is it possible to select an object only by clicking on it (and also many object if you press in the same time Ctrl (same behaviour with the black arrow)) ?

**Comment by ebocher** [comment]
any input ?

**Comment by nicolas-f** [comment]
There is no loading of all table.

It is possible to change the tool for a click selection.

**Comment by gpetit** [comment]
@nicolas-f Maybe you didn't checked but when you click on a new object (with the info tool), you can see that the table does not display immediately selected attributes. During a variable laps of time, you can see that ALL the table is displayed. To test, do this procedure with a table that has at least 50 000 lines.

Concerning the second point, could you please explain why this is not possible.

**Comment by nicolas-f** [comment]
When you do a new selection the filter is removed then it is applied. When the filter is removed the table data is **not** reloaded. Computation of the selected rows may take time depending on the row count, this is normal.

I think you have misread the second point.

**Comment by gpetit** [comment]
@nicolas-f Sorry for the second point. My bad. So do you think it's easy to upgrade this new behaviour ?

For the first point, it's not really clear for me. Ok the table is not reloaded (in a informatic point of view). But in a user point of view there is a lag ... Is there a way (a work around, ...) to solve this latency ?

**Comment by nicolas-f** [comment]
I will looking how to improve the user experience. 

Yes it should be easy to upgrade the behaviour, I will read how the black arrow is implemented.

**Comment by nicolas-f** [comment]
Do you feel it is a latency because there is no user feedback when OrbisGIS is computing the rows affected by the selection ?

**Comment by gpetit** [comment]
Not sure to understand your question.
In my "user" point of view, this latency is not user friendly and we should find a way to remove it

**Comment by nicolas-f** [comment]
If the operation take processing time, then the processing time cannot be removed. But we can show a progress to the user to tell him that OrbisGIS is computing the intersection between the InfoTool area and the table geometries.

**Comment by ebocher** [comment]
The pb is not on the processing time but on the user experience. 
It would be better to by pass the table loading between each filters.
I never seen that before. ;-)

**Comment by ebocher** [comment]
@gpetit What do you think about my comment ?

**Comment by gpetit** [comment]
+1 but the question is how to by-pass

**Comment by nicolas-f** [comment]
![mgc](https://cloud.githubusercontent.com/assets/1382241/23895882/ae07535e-08a7-11e7-88f3-c09dbc7faeec.gif)

**Comment by ebocher** [comment]
@nicolas-f 
Please do not post here this kind of humor.
By the way, this issue is clearly related to a code design.

**Comment by SPalominos** [comment]
@gpetit, @ebocher Does the latency problem still exists ? Is there an other problem  with the info tool ?

**Comment by ebocher** [comment]
Since the last fix, it's not possible to cancel a filter on the table after the infotool action.
When the infotool is used the message "Get rowset without opening it" appears in the output console.

**Comment by ebocher** [comment]
Fixed thanks a lot
