### ISSUE TITLE
Wps properties configuration

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1141]
Make the wps properties configurable by the user. They should also be saved and loaded.

**Comment by ebocher** [comment]
Do you have a list of  properties ?

**Comment by SPalominos** [comment]
Here is the list of the properties : [basicWpsServer.properties](https://github.com/SPalominos/orbisgis/blob/master/bundles/wps/wps-service/src/main/resources/org/orbisgis/wpsservice/utils/basicWpsServer.properties). Some of them will be optional.
