### ISSUE TITLE
Wps server accessible

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1144]
Make the Wps server be a real server : make it accessible (locally in the first step) to Wps client other than OrbisGIS, like QGIS.

Steps for the server side :
 - Adds an OSGI webserver to OrbisGIS
 - Connect to WPS server to the web server to expose the WPS request
 - Test locally the connection to the OrbisGIS web server with an other client
 - Test all the well running of the scripts with different kind of value (references or in-line value)
 - Same tests with a distant OrbisGIS wps server.

Steps for the client side (to be performed with different kind of Wps servers :
 - Test the connection to a external Wps server with a GetCapabilities request.
 - Test the displaying of process to test if the inputs/outputs are well recognized. (more specifically the mime type to encode the geo data like geojson, xml ...)
 - Test the execution of processes.
 - Test the get/download or the result of the executions.

**Comment by ebocher** [comment]
Could you please provide a more detailed info to resolve this issue ?
The main steps ?
Thx

**Comment by SPalominos** [comment]
Steps updated in the initial messages. Tell me if you have any question/comment.

**Comment by nicolas-f** [comment]
May be create a orbisgis-web-dist project for a limited set of OSGi bundles. 

Some links related to OSGi web server components:

https://github.com/entwinemedia/weblounge
http://servicemix.apache.org/
http://sling.apache.org/
http://blog.nanthrax.net/2012/12/how-to-enable-https-certificate-client-auth-with-karaf/
http://velocity.apache.org
http://felix.apache.org/documentation/subprojects/apache-felix-http-service.html
http://cocoon.apache.org/
http://en.wikipedia.org/wiki/Thymeleaf
https://wicket.apache.org/
https://ops4j1.jira.com/wiki/display/paxwicket/Pax+Wicket
https://github.com/ubersoldat/jongo
http://www.owlgraphic.com/owlcarousel/

**Comment by nicolas-f** [comment]
We need to avoid any xml/properties file except the pom.xml

Use annotation and declarative services to add new web page to the web server.

**Comment by nicolas-f** [comment]
I like Sling. They are very compatible with the current OrbisGIS framework and it does not require writing configuration files.

We can use OSGi declaratives services annotation:

**Comment by SPalominos** [comment]
Nice, thank you, we will give a look to it !

**Comment by ebocher** [comment]
Thanks a lot @nicolas-f

**Comment by SPalominos** [comment]
Move into the repository OrbisWPS : orbisgis/orbiswps#11
