### ISSUE TITLE
Batch script ui broken

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1167]
The last PR breaks the bash script UI.
Have a look on "Geometry properties" or "Buffer(s)" scripts 
Please test more before sending a PR.

@gpetit 
Could you test ? Maybe I'm wrong.

**Comment by gpetit** [comment]
It works for me (release of 08/02/17) (I tested "Geometry properties" and "Reproject geometries"

But the UI is verrryyyy slow (I mean, just the loading of the toolbox and also the selection of parameters (list of tables, fields, ...)

**Comment by ebocher** [comment]
Ok for me nothing appears
