### ISSUE TITLE
Progress Monitor for wps job

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1169]
ProgressMonitor would be very useful to manage and to follow the progress of the execution of a WPS process. The progression will be displayed in the OrbisGIS UI without the need of the LogEditor.
But now, it needs to use a SwingWorkerPM which creates a dependency to Swing, that can't be done for the WPS server.
The solution could be to create and interface, that would be implemented in SwingWorkerPM, which contains the methods to track the ProgressMonitor.

**Comment by nicolas-f** [comment]
Why we can't use a SwingWorker under WPS Server ? I don't think it will fail with a HeadLess exception. You can try run wps server with the following option to test it ``-Djava.awt.headless``
