### ISSUE TITLE
Database Connection Pooling ?

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1175]
Do we need to add a JDBC connection pooling instead of a standard JDBC connection ?

as : 
https://github.com/brettwooldridge/HikariCP

@nicolas-f @SPalominos

**Comment by nicolas-f** [comment]
The h2 connection keep alive time make this kind of operation useless. However I don't know for PostGIS. Do you have connection issues with PostGIS ?

**Comment by ebocher** [comment]
nope So I close this question
