### ISSUE TITLE
BoundingBox Data

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1180]
Add support to the BoundingBox Data as input and output.
Note that a BoundingBox : 

- could have a  reference to a CRS definition. 
- a dimension 2 or 3
- is defined by 4 values as example:  51.9,7.0,53.0,8.0

So in the UI we can have

Examples : 
 51.9,7.0,53.0,8.0,EPSG:4326 
 51.9,7.0,53.0,8.0,2, EPSG:4326 where 2 is the dimension
 51.9,7.0,53.0,8.0,2 -> use the default CRS
 51.9,7.0,53.0,8.0  -> use default CRS and dimension

more information for  XML encoding http://docs.opengeospatial.org/is/14-065/14-065.html#28

**Comment by ebocher** [comment]
Add support to the 3D BB
Add copy paste icon with a tooltip

**Comment by ebocher** [comment]
Tested with this approach

```java
@BoundingBoxInput(
    title = ["Input bounding box","en","Zone d'extraction","fr"],
    description = ["The input bounding box to extract data from the OSM server.","en",
                "Zone d'extraction pour télécharger les données du serveur OSM.","fr"],
    dimension ="2",
    supportedCRSList=["EPSG:4326"])
    )
Geometry bbGeometry

```
But it returns an error.
Could you please provide an example ?

**Comment by SPalominos** [comment]
I might be just a problem on the attribute name.
Does that work ?
```java
@BoundingBoxInput(
    title = ["Input bounding box","en","Zone d'extraction","fr"],
    description = ["The input bounding box to extract data from the OSM server.","en",
                "Zone d'extraction pour télécharger les données du serveur OSM.","fr"],
    dimension ="2",
    defaultCRS="EPSG:4326")
    )
Geometry bbGeometry

```

**Comment by ebocher** [comment]
It returns

```java
'java.lang.String' in @org.orbisgis.wpsgroovyapi.attributes.BoundingBoxAttribute
 @ line 47, column 16.
       dimension ="2",
```

**Comment by ebocher** [comment]
Sorry it works with dimension = 2
however defaultCRS="EPSG:4326" list all CRS and not only the EPSG:4326

**Comment by ebocher** [comment]
```java
@BoundingBoxInput(
    title = ["Input bounding box","en","Zone d'extraction","fr"],
    description = ["The input bounding box to extract data from the OSM server.","en",
                "Zone d'extraction pour télécharger les données du serveur OSM.","fr"],
    dimension =2,
    defaultCRS="EPSG:4326",
    supportedCRS=["EPSG:4326"]
    )
Geometry bbGeometry
```
returns 

Unable to parse the process file:/home/ebocher/Autres/codes/orbisgis/bundles/wps/wps-service-scripts/src/main/resources/org/orbisgis/wpsservicescripts/scripts/Import/importOSMFromServer.groovy.
The script is not valid.

**Comment by SPalominos** [comment]
It's a problem on my side, the fix is coming.

**Comment by ebocher** [comment]
Add a message when the user set
dimension ="3",

The 3D Bounding Box is not yet supported.

**Comment by ebocher** [comment]
I think the bouding box UI must be simplified.
The user must set only  51.9,7.0,53.0,8.0,EPSG:4326 in a textfield.
But list of CRS must be masked. 
@gpetit and @SPalominos

**Comment by gpetit** [comment]
Under the text area dedicated to the bbox geometry, add a line to specify the CRS.

Here you have:
- a drop-down list with at least the default CRS
- if nothing is specified, a list of all CRS
- if some CRS are specified, the list of supported CRS (with a popup message "Only supported CRS are listed")
