### ISSUE TITLE
Ubuntu repository 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1183]
Update the OrbisGIS website to explain how to install the ppa

https://launchpad.net/~orbisgis/+archive/ubuntu/orbisgis-unstable

**Comment by gpetit** [comment]
I'm on it

**Comment by gpetit** [comment]
Done : http://doc.orbisgis.org/en/latest/users/install.html#ubuntu-ppa-repository
@ebocher you can have a look and close
