### ISSUE TITLE
Open attributes even if there is no data in Geocatalog

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1190]
Even if you don't have any tables in the Geocatalog (e.g when you start with a new empty workspace), when you make a right-click, you have the option "Open attributes".

It make no sense. This option should be display only if there is already data loaded.

@ebocher @SPalominos

**Comment by ebocher** [comment]
It will be fixed with the import WPS scripts

**Comment by ebocher** [comment]
Maybe just add a test on the Open attributes plugin

**Comment by ebocher** [comment]
Thanks
