### ISSUE TITLE
Documentation about link/import

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1193]
In this file http://doc.orbisgis.org/en/latest/users/quickstart.html#load-data

May be add more information about the difference:

- Add: Link a new database table to a file (vector, alphanumeric, ...),
  - Pro: 
    - Immediate table creation
    - Does not take more disk space
    - Can create spatial index
   - Cons:
     - Read-only table
     - Cannot create alpha-numeric index
     - Only compatible with h2 database
- Import: Copy the file content into a new database table,
  - Pro: 
    - Create a native h2/PostGIS table.
    - Read/Write table
    - Can create spatial index and alpha-numeric index
   - Cons:
     - Take time to create the table depending on file size
     - Take more disk space

**Comment by gpetit** [comment]
+1 I'm also currently preparing a schema to illustrate a bit more this part

@ebocher

**Comment by gpetit** [comment]
@nicolas-f Done. Please check http://doc.orbisgis.org/en/latest/users/quickstart.html#load-data

**Comment by nicolas-f** [comment]
Approved 👍

**Comment by gpetit** [comment]
Thx Chuck
