### ISSUE TITLE
WPS identifier hierarchy

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1209]
Now all the identifiers in a WPS process must be unique, so an identifier of an output/input can be sometimes quite long. It must be change, the identifier of an input is build from the one of the process :
``` groovy
@Process(identifier = "my:process:identifier")
...
@Input(identifier = "input:identifier")
...
```
The process identifier is `"my:process:identifier"` and the input identifier is `"my:process:identifier:input:identifier"`

**Comment by ebocher** [comment]
Sounds good.
Could you please post a use case with a java code to load a process and set input an output values ?
It's just to see if we have not left anything out
