### ISSUE TITLE
OrbisGIS external folder in sources

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1212]
What about deleting the [external] (https://github.com/orbisgis/orbisgis/tree/master/external) folder in OrbsGIS and use only the https://github.com/orbisgis/orbisgis_osgi-dependencies ?

**Comment by nicolas-f** [comment]
The goal of external folder is not to have to publish on maven our own derived jar of external libraries.

If you are using orbisgis_osgi-dependencies you will have to publish the jars on maven.

Morover in orbisgis-dist, the managing of jar maven versions is simple as all projects in external folder use the same maven version as OrbisGIS (but the real bundle/packages versions are kept in the manifest)

So you can change it, but the managing will be more complex.

Is JTS has already an OSGi manifest now ?

**Comment by nicolas-f** [comment]
orbisgis_osgi-dependencies is used for OrbisGIS plugins only

**Comment by ebocher** [comment]
The last JTS released will have an OSGi manifest.

Using two repositories to manage dependencies could be  a risk because of duplicated dependencies and not up to date.

**Comment by nicolas-f** [comment]
The real bundle/packages versions are kept in the manifest. So if there is a version issue OSGi will stop the integration of the wrong bundle.
