### ISSUE TITLE
WPS clean up

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1215]
The code for the WPS bundle modules must be cleaned and checked.

**Bundle WPS Service**

Complete javadoc (methods and arguments) on 

Class DataProcessingManager on  preProcessData , postProcessData
Class ProcessExecutionListener 
Class Parser complete doc for defaultvalue 
Class ProcessParser 
Classes ProcessIdentifier, Job , DataType, ObjectFactory , LocalWpsServer

Why isSpatialType(DataType dataType) in DataType doesn't support geometrycollection and LinearRing ?

In WpsServerProperties what about if File propertiesFile = new File(coreWorkspace.getWorkspaceFolder() + File.separator + SERVER_PROPERTIES);
            is null ?

In LocalWpsServerImpl : 

private static final String WPS_SCRIPT_FOLDER = "Scripts"; never used 

Several todo must be remove
Eg
//TODO Remove this user message and implements the parallel process execution
            if (!multiThreaded) {

By the way, multiThreaded = testDBForMultiProcess(); never used 

**Bundle WPS Service script**

In WpsScriptsPackage
Possible null value on 
listIdProcess.add(pi.getProcessDescriptionType().getIdentifier());

**Bundle WPS Client**

Complete javadoc (methods and arguments) on 

InternalWpsClientHandler, BoundingBoxDataUI

In EnumerationUI several possible null values

In GeometryUI, getDefaultValue(DescriptionType inputOrOutput) boolean isOptional = false; seems never used

In JDBCTableFieldUI, JDBCTableFieldValueUI, JDBCTableUI idem

**Comment by SPalominos** [comment]
Moved into the repository OrbisWPS : orbisgis/orbiswps#13
