### ISSUE TITLE
Remove calls to bundleContext.getServiceReference

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1217]
Please remove calls to bundleContext.getServiceReference as it may raise Null pointer exception and break bundles services cycles.

https://github.com/orbisgis/orbisgis/blob/master/bundles/orbisgis-omanager/src/main/java/org/orbisgis/omanager/ui/ActionDeploy.java#L117

**Comment by ebocher** [comment]
What about https://github.com/orbisgis/orbisgis-official-plugins/blob/master/chartView/src/main/java/org/orbisgis/chart/ChartFactory.java#L192 ? is it the same issue ?

**Comment by nicolas-f** [comment]
I think you created theses static class for Groovy. But do not forget to call [BundleContext.ungetService](https://osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleContext.html#ungetService(org.osgi.framework.ServiceReference)) when the service is not used anymore.

**Comment by ebocher** [comment]
We must check all bundles and all plugins to fix this issue.

**Comment by nicolas-f** [comment]
There is a single bundle that call this function. And also in groovy script.

If our Groovy parser could be able to declare a new osgi bundle from script it would be wonderfull. Maybe somebody has already done this or it will be done.

OSGi was done also in order to exchange plugins accross softwares.

**Comment by ebocher** [comment]
@SPalominos  any idea about @nicolas-f comment's

**Comment by ebocher** [comment]
Is it still valid ?

**Comment by nicolas-f** [comment]
It seems it has been removed
