### ISSUE TITLE
Extract LocalWpsServerImpl from wps-service bundle

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1221]
#### Update:

- Split the `wps-client` into : `orbiswps-client` (the API) and toolbox-editor (the implementation)
- Split `wps-service` into : `orbiswps-server` (the API and the base implementation) and moves the methods having dependencies to OrbisGIS bundles into the `toolbox-editor`
- Split `wps-script` into : `orbiswps-script` (the API and the implementation) and `toolbox-ui-action` (the methods to add action in the other bundles => issue #1129)
- Rename `wps-groovy-api` into `orbiswps-groovy-api`

Then move in other project `orbiswps` the bundles `orbiswps-client`, `orbiswps-server`, `orbiswps-script`, `orbiswps-groovy-api`

#### Original issue
The class LocalWpsServerImpl is a WpsServerImpl extension to be used with OrbisGIS and its WPS client while the class WpsServerImpl is a standalone WPS server which doesn't need OrbisGIS to work.
So, LocalWpsServerImpl will be moved into a new bundle called wps-service-orbisgis.

**Comment by SPalominos** [comment]
I'm on this issue.

**Comment by ebocher** [comment]
LocalWpsServerImpl must be linked to the datamanager and the setDatasource must be removed.

**Comment by ebocher** [comment]
add addGroovyProperties and removeGroovyProperties on the WPSServer instance

**Comment by ebocher** [comment]
This issue is re-open because the extraction is not yet finished

**Comment by ebocher** [comment]
Todo : 

-  addProcess(File f, String[] iconName, boolean isRemovable, String nodePath) must be change to public List<ProcessIdentifier> addProcess(File f)
- if addProcess(File f, String[] iconName, boolean isRemovable, String nodePath)  is implemented within  the OrbisGISWPS implementation what about Mapuce-Tools ?
- the method to copy scripts from a path to the WPS script folder must be added in WPSUtils class
- WPSServerImpl init() and init(string) must be clarified. Do we need to extend the constructor ?
