### ISSUE TITLE
Add Legend when export image from the map editor

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1231]
Hi,

It could be great if, when we export an image from the map editor, we could add the legend, the north and a scale (https://adeorun.com/medias/echelle-carte-1200x628.jpg).

Best regards,

Pierre

**Comment by ebocher** [comment]
You must used the mapcomposer plugin to create a map layout to add furnitures to the map as a scale, a title.
Display and export legend are planed with the new SE style specification.

**Comment by pierromond** [comment]
Thank you !
