### ISSUE TITLE
Legend colors

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1232]
In the style editor, is it possible to reverse the colors of the color scheme ? 
Example: OrRd -> from red to white

**Comment by gpetit** [comment]
Not right now. The color scheme are mainly coming from ColorBrewer (I don't if it's [v1](http://www.personal.psu.edu/cab38/ColorBrewer/ColorBrewer.html) or [v2](http://colorbrewer2.org/)) and are therefore predetermined.
@ebocher

**Comment by pierromond** [comment]
Maybe something could (blind for the user) "reverse" the data and not the color scheme.

**Comment by gpetit** [comment]
I don't think this should be complicated to reverse the color scheme, but need to put it in the loooonnnggg todo list ;-)

**Comment by pierromond** [comment]
ahahah :) ok ! by the way, it is not a so important feature.

**Comment by ebocher** [comment]
I propose to replace the button  by a checkbox with the the text  "revert"

**Comment by ebocher** [comment]
Perfect
