### ISSUE TITLE
Cannot display a postgis linked table 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1245]
The query

```sql
CREATE LINKED TABLE USR_TEMP ('org.orbisgis.postgis_jts.Driver', 'jdbc:postgresql_h2://?:5432/mapuce','?', '?',  'lienss', '(SELECT * FROM lienss.usr limit 100)')
```
Works well but OrbisGIS is not able to renderer the table or show the attributes.

**Comment by ebocher** [comment]
Find a solution here https://github.com/h2database/h2database/issues/507

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
I'm not able to fix this issue due to the complexity of readrowset architecture.
The pb  is now  : 

CREATE LINKED TABLE USR_TEMP ('org.orbisgis.postgis_jts.Driver', 'jdbc:postgresql_h2://?:5432/mapuce','?', '?',  'lienss', '(SELECT * FROM lienss.usr limit 100)')

The USR_TEMP can be loaded by the tableeditor but the TOC is not able to draw the table due to an empty pk that returns a bad SQL syntax.

Any idea ?

**Comment by SPalominos** [comment]
Seems to be linked to #996.

**Comment by SPalominos** [comment]
I'm on it.

**Comment by SPalominos** [comment]
The PullRequest #1274 adds a workaround which will be removed once H2 has been patched. On the PR merged, this issue will be moved to the OrbisGIS 5.2 milestone.
