### ISSUE TITLE
Problem to install R console

### ISSUE THREAD

**Issue by JacquessonL** [orbisgis/orbisgis#1246]
Hello, 

I am trying to install the plug-in "R console" in OrbisGis through the plug in manager, and I have the following error message :

Resolver: Install error - org.orbisgis.aether-impl-osgi

Do you know what could be the problem ?

**Comment by ebocher** [comment]
Seems a pb with our plugin repository. 
@SPalominos  Could you please check this issue ?

**Comment by SPalominos** [comment]
I'm on it.

**Comment by SPalominos** [comment]
In the very last OrbisGIS version downloaded from the website (5.1.0-SNAPSHOT-2017-05-23) the installation works on my machine.
@JacquessonL Which version of OrbisGIS are you using ? And what is the OS you are using (Windows, Linux, version) ?

**Comment by pierromond** [comment]
Just to add some info, I have the same problem on my professional computer (same network than @JacquessonL ) with the following error: Resolver: Install error - org.orbisgis.commons-vfs2-osgi

OrbisGIS version : 5.1.0-SNAPSHOT-2017-05-23
Windows 7 Professionnel

BUT... It works on my personal computer 4G connected. Should we suspect the network ? we are actually connected via the proxy: java -jar -Xmx%mem%M  -Dhttp.proxyHost=137.121.61.4 -Dhttp.proxyPort=3128 -jar orbisgis.jar --nofailmode

**Comment by nicolas-f** [comment]
You have to set the proxy in OrbisGIS gui also.

![image](https://cloud.githubusercontent.com/assets/1382241/26347535/2d64d188-3faa-11e7-9c48-670f7cba67af.png)

**Comment by JacquessonL** [comment]
Thanks!

**Comment by SPalominos** [comment]
Thank you @nicolas-f !
