### ISSUE TITLE
"Add" & "Import" difference is not very user-friendly

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1247]
Each time that I want to import data, I get a little confuse. I know that one of the two possibilities "add/import" copy the database during the importation and not the other one, but I never remember which term is for which functionality. 

Maybe it could be possible to change for "Import" and "Import & copy" or sthg like that ? 
I don't find any better idea for now.

**Comment by ebocher** [comment]
Sure.
I propose to update the menu  
Add by Link to (a file or a database)

@gpetit

**Comment by gpetit** [comment]
Or maybe just 
* Link to
   * a file
   * a folder
   * a database
* Import
   * a file
   * a folder

**Comment by SPalominos** [comment]
I'm on it.

**Comment by ebocher** [comment]
thanks
