### ISSUE TITLE
Bug on "Same value" tool

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1249]
In the attributes table, we have the "Select same rows" tools.

If there is special character such as ' in the text value, the tool doesn't work

Below is the output log for a query on the region called "PROVENCE-ALPES-COTE-D'AZUR"
```
SELECT "PK" FROM DEP_FRANCE WHERE  "NOM_REGION"::text = 'PROVENCE-ALPES-COTE-D'AZUR'
```

We have to take into acount such cases.

@ebocher @nicolas-f @SPalominos

**Comment by ebocher** [comment]
@gpetit  fixed by @SPalominos 
Could you please confirm ?

**Comment by gpetit** [comment]
Great. Thanks @SPalominos
