### ISSUE TITLE
Groovy : pb lorsque 2 requêtes SQL dans une commande

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1250]
I tried the following command in Groovy, city being a String :
`sql.execute("drop table if exists TMP_DATA; create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES where CITY = ${city}")`

but it does not work. I got the error "Invalid value "1" for parameter "parameterIndex" [90008-195]". To make it work, it is necessary to split the command :

`sql.execute("drop table if exists TMP_DATA")`
`sql.execute("create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES where CITY = ${city}")`

**Comment by ebocher** [comment]
This kind of syntax works well
```
sql.execute("drop table if exists TMP_DATA; create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES limit 2")
```
but  this one doesn't work

```
sql.execute  "drop table if exists TMP_DATA; create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES LIMIT  :size", size:1

```
even if there is an example here explained here http://docs.groovy-lang.org/latest/html/documentation/sql-userguide.html,

**Comment by ebocher** [comment]
@j3r3m1  is it still available ?

**Comment by ebocher** [comment]
Could you test
"drop table if exists TMP_DATA; create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES where CITY = ${city}".tostring

**Comment by j3r3m1** [comment]
OK it works slightly modifying your command (${city} should be between '). The good command is the following
`sql.execute("drop table if exists TMP_DATA; create table TMP_DATA as select * from DATA_APPRENTISSAGE_CITIES where CITY = '${city}'".toString())`

**Comment by ebocher** [comment]
super
