### ISSUE TITLE
"Table not found" when "drop table if exist"

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1251]
The following error is displayed in the log when a "table if exists TOTO" query is run through
a groovy command whereas nothing happened using directly the SQL console :
`Table "TOTO" not found`

**Comment by ebocher** [comment]
So you mean that the SQL console must show the message 'Table "TOTO" not found'

**Comment by j3r3m1** [comment]
No the contrary. In my opinion, nothing should happen using the query
`drop table if exists;`
 even if run in a groovy script.

**Comment by gpetit** [comment]
So we should have the same behaviour between Groovy and SQL Consoles.
If the table TOTO does not exists, the Groovy console should not return any error message.

Currently, if you don't have a table called TOTO and if you run "drop table if exists TOTO;" in the SQL Console, you obtain this in the output console

```
Execute request 1/1: drop table if exists TOTO
Done in 0,008 seconds

OVERALL EXECUTION TIME: 0,058 seconds
```

**Comment by SPalominos** [comment]
@j3r3m1 On my side, with the last  OrbisGIS version (04/12), if I run `sql.execute("DROP TABLE TOTO IF EXISTS")` in the groovy console, nothing happen expect a log message `Groovy script executed in 0,033 seconds`. Is that the desired behaviour ?

**Comment by j3r3m1** [comment]
Yes it is the desired behaviour. I tested the last version it works well.
