### ISSUE TITLE
Impossible to launch Orbisgis v5.1.0 with Java JRE-9.0.1 or JRE-8u151 and Win7 64bits OS

### ISSUE THREAD

**Issue by nahtanojoal** [orbisgis/orbisgis#1256]
The following message error is displayed when I try to launch the orbisgis.jar file : "orbisgis nécessite au minimum java 1.7+" ("orbisgis requires at least java 1.7+").

My laptop conf. :
Windows 7 Home Premium Edition 64 bits SP1
JAVA JRE-9.0.1, then JAVA JRE-8u151 

I fixed it by using JAVA v7 (JRE-7u80).

**Comment by gpetit** [comment]
Thanks for this report ... and welcome in the team @nahtanojoal ;-)

**Comment by SPalominos** [comment]
I'm on it.

**Comment by nicolas-f** [comment]
Users that use Java 9 will not understand:
`OrbisGIS needs at least a java 1.7+`

If version is < that 1.7 or >= 1.9 then display something like that:
`Your version of Java is X.XX , Orbisgis is working only with Java version 1.7 and 1.8 . Please install and activate a compatible version of Java.`
