### ISSUE TITLE
Setup an issue template on this repo

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1258]
In order to get more detailed and helpful issues we should setup an issue template (default text when creating an issue)

The guide is here:

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ebocher** [comment]
Ok feel free to suggest a template

**Comment by gpetit** [comment]
Done @nicolas-f

**Comment by nicolas-f** [comment]
Sorry, I give the wrong link for issue template:

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by gpetit** [comment]
Should be ok right now @nicolas-f ;-)
