### ISSUE TITLE
Display name of @EnumerationInput with WPS client

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1259]
The script
```java
@EnumerationInput(
		title = ["Operation","en",
				"Opération","fr"],
		description = [
				"Operation to extract the points.","en",
				"Opération d'extraction des points.","fr"],
        values=["st_intersects", "st_contains"],
        names=["Intersects", "Contains"])
String[] operation = ["st_intersects"]
```
doesn't show the names ["Intersects", "Contains"] but the values ["st_intersects", "st_contains"].

**Comment by ebocher** [comment]
My fault the bug is due to the client that is not able to refresh a script that has been modified.

**Comment by ebocher** [comment]
@SPalominos Could you please check the refresh button ? It seems it doesn't work.

**Comment by SPalominos** [comment]
If you do not want to translate, you can use that : `names=["Intersects, Contains"]`

**Comment by ebocher** [comment]
ok thanks
