### ISSUE TITLE
NetworkFunctions not avaible with the last snaphot

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1261]
The graph functions available in H2gis-Network via NetworkFunctions class are not available from OrbisGIS.
Moreover, the plugin manager shows a wrong bundle for the h2network that refers to an old version.

**Comment by ebocher** [comment]
Even if the bundle is installed from the plugin manager, the query
```
CREATE ALIAS IF NOT EXISTS H2GIS_NETWORK FOR "org.h2gis.network.functions.NetworkFunctions.load";
CALL H2GIS_NETWORK();
```
is not able to load the graph function.

**Comment by SPalominos** [comment]
I'm on it.

**Comment by SPalominos** [comment]
So, everything is OK. To load H2GIS-Network, you have to : 
 - Install the plugin throw the plugin manager.
 - Restart OrbisGIS in the normal mode (not in the safemode or without the -clean option"
 - call `CREATE ALIAS IF NOT EXISTS H2GIS_NETWORK FOR "org.h2gis.network.functions.NetworkFunctions.load";
CALL H2GIS_NETWORK();` to load the network functions.

**Comment by SPalominos** [comment]
Has it works, the issue it postponed to 5.2.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
