### ISSUE TITLE
Bundles must be updated from the plugin manager

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1262]
The OrbisGIS bundles (plugins) must be udpated from the plugin manager.

**Comment by ebocher** [comment]
@gpetit

**Comment by gpetit** [comment]
You mean we should update the list of available plugins to keep only those that are compliant with the OrbisGIS version (e.g the 5.1) ?

**Comment by SPalominos** [comment]
I'm on it.

**Comment by gpetit** [comment]
Difficult to check since there is no OrbisGIS version info attached to each plugins (and which we can use to see if there is plugins that should not been listed in the plugin manager). Anyway, the job seems to be done (thanks @SPalominos )
@ebocher IMO you can close this issue
