### ISSUE TITLE
Geometry in log

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1287]
When you have an error on a SQL query which is done on a geometry, the whole request and the whole geometry are displayed inside the log. With a complex geometry, the log can be full very quickly and it's hard or impossible to see the whole request.

It would be great a handle this kind of error to make it more simpler to read. Some idea :
 - do not displaythe whole geometry 
 - make the geometry text clickable which open the table editor with the good line selected
 - Write the error inside a SQL table

**Comment by gpetit** [comment]
+1 for the error table

**Comment by ebocher** [comment]
I'm in favour of the first proposal.
Because
make the geometry text clickable which open the table editor with the good line selected needs some work ;-(
Write the error inside a SQL table may pollute the database

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
