### ISSUE TITLE
Auto clean the log

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1288]
When OrbisGIS generate big error messages (Like SQL error on request with very by geometries), the log file size increase quickly. It should have a maximum size to avoid to fill up the user disk.

**Comment by ebocher** [comment]
I propose to use a Rolling Based on File Size technique ?
See https://www.baeldung.com/java-logging-rolling-file-appenders

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
