### ISSUE TITLE
Impossible to stop a groovy or SQL script

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1290]
#### 1- Specifications 

* OrbisGIS version: 5.1.0
* Java version: 1.8.0_151
* Operating System: Xubuntu 16.04

#### 2- Expected behavior and actual behavior
I would like to stop my SQL or Groovy script during the process. I click on the red cross on the bottom right of the orbisGIS window.

The script should stop but actually it keeps on running up to the end.

#### 3- Steps to reproduce the problem
Use any script using a sufficiently big amount of data to have the time to stop the process...

**Comment by SPalominos** [comment]
For groovy it has been fixed, but for SQL things are quite different.
As Groovy is executing a whole script, the only way to stop it is to run it in a separated thread and to stop it.
For SQL script, the request are executed one by one and it it is closed, OrbisGIS wait the finishing of the running request and then avoid executing the other request. By doing that, it avoid problems with the database.
