### ISSUE TITLE
Empty Toolbox

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1295]
#### 1- Specifications 

* OrbisGIS version: 5.1 (snapshot 01/02/2018)
* Java version:1.8
* Operating System: Windows

#### 2- Expected behavior and actual behavior
Expected behavior: See some WPS scripts
Actual behavior: the Toolbox is empty

Any idea ?
(Attached the log file)
[orbisgis.log](https://github.com/orbisgis/orbisgis/files/1685635/orbisgis.log)

**Comment by SPalominos** [comment]
Fixed.
