### ISSUE TITLE
Import file in a PostGIS db

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1300]
#### 1- Specifications 

* OrbisGIS version: 5.1-dev
* Java version: 8
* Operating System: Linux

#### 2- Expected behavior and actual behavior

When OrbisGIS is connected on a PostGIS database, the import menu does nothing.

#### 3- Steps to reproduce the problem

Connect OrbisGIS with PostGIS, go to the Geocatalog module, right clic to select the Import file menu.

**Comment by gpetit** [comment]
Can not reproduce. Works well for me. I just connected to a PostGIS db (remote, not local) and imported a shp file. The new table is well created in the "public" schema and I can display geometries into the map.

**Comment by ebocher** [comment]
Try to connect on risingdb

**Comment by gpetit** [comment]
Yes, I'm on it (I imported the "limite_commune" table in the public schema)

**Comment by ebocher** [comment]
Without any pb ?
If yes you can close it

**Comment by gpetit** [comment]
No pblm.
