### ISSUE TITLE
Impossible to do right click on Toolbox (windows)

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1301]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 1.8
* Operating System: Windows 

#### 2- Expected behavior and actual behavior

It should be possible to import WPS scripts using a right click on the toolbox. When I do the right click, nothing happens !

#### 3- Steps to reproduce the problem

Good question !

**Comment by ebocher** [comment]
@pierromond could you test  ?

**Comment by pierromond** [comment]
Arf ! still doesn't work !

Wait ... trying in safe mode ....

It works !!!! Thank you 👍 👍 👍 🥇

**Comment by ebocher** [comment]
Are you using the last OrbisGIS version?
Did you run orbisgis -clean
Sorry for that ;-)
