### ISSUE TITLE
Facilitate fencing

### ISSUE THREAD

**Issue by arnaudcan** [orbisgis/orbisgis#1304]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: ??
* Operating System: Windows

#### 2- Expected behavior and actual behavior
I want to create a fence on a large area on the MapEditor, but I loose the fence when I navigate on the area. Initially, I wished to create a multi-points lasso selection (list of hand-placed acoustical receivers) on this large area...

#### 3- Steps to reproduce the problem
No idea.

**Comment by gpetit** [comment]
Hi @arnaudcan . You mean, you loosed the fence because you moved into the map (you changed the scale level and the bbox) ?

**Comment by nicolas-f** [comment]
De/Zooming while creating a fence cancel the fence creation.

**Comment by ebocher** [comment]
It would be nice to keep the fence visible when De/Zooming

**Comment by ebocher** [comment]
@nicolas-f  any plan to take into account my comment ?

**Comment by nicolas-f** [comment]
I think I do not achieve that.

**Comment by ebocher** [comment]
Ok thanks
