### ISSUE TITLE
Map editor "geometry selection tool"

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1306]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 1.8
* Operating System: Ubuntu 17.10

#### 2- Expected behavior and actual behavior
When using the "geometry selection tool", I would like to select geometry that intersect my selection rectangle. If I start my selection rectangle from its top left corner, the selection only contains geometries entirely included in my selection rectangle. I need to start from the bottom right corner to make the selection work as I would like. It is OK but far from obvious.

I would suggest using a key like "Control" to select all the geometries that intersect the selection rectangle. An indication could appear on the bottom left of the "Map editor" when selecting the "selection tool" informing that pressing the key "Control" would select each geometry intersecting the selection rectangle.

**Comment by gpetit** [comment]
Hum ... why not.
Just to clarify, it's not necessary from "**top** left corner" or "**bottom** right corner". It just:
* from right to left --> intersects
* from left to right --> contains

**Comment by j3r3m1** [comment]
OK then simply display this information to the user when he select the "selection tool" could make easier its use ?

**Comment by gpetit** [comment]
Yes +1

**Comment by ebocher** [comment]
Yes. We must used the same method as in measure angle tool.

**Comment by gpetit** [comment]
Euh ... I don't know if it's the good example ;-) This tool is totally weird for me

**Comment by nicolas-f** [comment]
What is exactly the one line message to display to the user ?

**Comment by ebocher** [comment]
@gpetit ?

**Comment by j3r3m1** [comment]
Based on gpetit answer, I propose:
selection from left to right : st_intersects
selection from right to left : st_contains

Or if the space sufficient:
selection from left to right : all objects intersecting the selection zone are considered
selection from right to left : all objects contained in the selection zone are considered

**Comment by ebocher** [comment]
I propose to create two buttons in the toolbar :  first one for intersects and the second one for contains

**Comment by j3r3m1** [comment]
+1

**Comment by ebocher** [comment]
I m on it

**Comment by ebocher** [comment]
Fixed
