### ISSUE TITLE
Filtering compatible bundles

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1307]
Currently the list of downloadable plugins display all compatible and incompatible plugins.

However there is a method to display only the compatible plugins.

The Resolver service (org.osgi.service.obr.Resolver) is able to check if a bundle can be successfully installed before it is downloaded (thanks to the downloaded obr.xml)

This class is already used by OrbisGIS when the user click on Download&Install:

https://github.com/orbisgis/orbisgis/blob/master/bundles/orbisgis-omanager/src/main/java/org/orbisgis/omanager/ui/ActionDeploy.java#L147

The issue is this operation is cpu intensive (I think). Then the resolve must be done in a non-gui process and the user must be aware that all plugins are not displayed yet (because of Resolve currently applied on each bundle).

**Comment by gpetit** [comment]
This issue is more or less linked to #1262 no ?
