### ISSUE TITLE
Table with '.' in its name

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#1308]
#### 1- Specifications 

On all OrbisGIS / JAVA version, in the toolbox

#### 2- Expected behavior and actual behavior

A table with a '.' character in its name cause an error as the point is parse as schema/table separator

#### 3- Steps to reproduce the problem

Try to manipulate a table with a '.' in its name on the toolbox.

**Comment by ebocher** [comment]
Maybe related to OrbisWPS

**Comment by SPalominos** [comment]
It's mainly related to the toolbox which should "escape" the character when it creates the TableLocation.

**Comment by ebocher** [comment]
Seems for me a pb in the file name.
Not in the TableLocation code.
Is this kind of table name supported by SQL "TATA.TOTO" where TATA.TOTO is the shape file name ?

**Comment by ebocher** [comment]
Do we need in the H2GIS file drivers to replace the . with another character like _?
@SPalominos @nicolas-f

**Comment by ebocher** [comment]
I'm on it

**Comment by nicolas-f** [comment]
H2GIS is properly preserving requested table name, by using quotes to separate schema and database name

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
