### ISSUE TITLE
OrbisGIS stops refreshing the geocatalogue

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1310]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 8
* Operating System: UBUNTU 17.10

#### 2- Expected behavior and actual behavior
The warning message "Update table state (100%)" appear on the lower right of OrbisGIS and I can not remove it. I can run SQL scripts, it does work (messages appear on the "Sortie" box that processed were run) but nothing happen on the GeoCatalogue. I try resfreshing it but is does not change.

**Comment by nicolas-f** [comment]
Ouch
![image](https://user-images.githubusercontent.com/1382241/36587183-a8093880-1884-11e8-87c8-ed8c72c8c3d1.png)

**Comment by gpetit** [comment]
@nicolas-f or @SPalominos any idea ?

**Comment by nicolas-f** [comment]
I can't reproduce this issue anymore. May be it has been fixed by @SPalominos ?

**Comment by ebocher** [comment]
So we close it.
Thanks a lot

**Comment by SPalominos** [comment]
@nicolas-f Not specific fix has been done for this issue, we should keep an eye on it and reopen the issue if it happens again
