### ISSUE TITLE
TimeStamp in log file

### ISSUE THREAD

**Issue by pierromond** [orbisgis/orbisgis#1313]
#### 1- Specifications 
* OrbisGIS version: 5.1
* Java version: 1.8 
* Operating System: Windows 

#### 2- Expected behavior and actual behavior
Could it be possible to get a timestamp in the log file ?

**Comment by nicolas-f** [comment]
Yes.

Edit the file \user\.OrbisGIS\5.1\logback.xml

Update the pattern line to this:
```xml
<pattern>%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg%n %ex{full}</pattern>
```

More documentation on this site:
https://logback.qos.ch/manual/configuration.html

**Comment by ebocher** [comment]
@gpetit 
What about a specific entry on the wiki ?

**Comment by gpetit** [comment]
Ok, I'm on it

**Comment by gpetit** [comment]
Here is the result : https://github.com/orbisgis/orbisgis/wiki/09.-Custom-logging-messages
Feel free to edit/correct or giving me advices to improve this page if needed.

**Comment by gpetit** [comment]
@pierromond if it's ok for you maybe we can close this issue ?

**Comment by pierromond** [comment]
It is perfect ;)
