### ISSUE TITLE
Bug when copy geom into Console

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1316]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 8
* Operating System: Ubuntu 16.04 

#### 2- Expected behavior and actual behavior

* I have a geometry in a table This geometry has z coordinates. 
* Then I just copy he geom (click on a cell, and CTRL+C).
* And paste (CTRL+V) this geometry into the SQL Console. --> the geom has no more z coordinates

Ex: `LINESTRING (1 2, 2 2 2, 4 2 2, 5 2)` in the table becomes `LINESTRING (1 2, 2 2, 4 2, 5 2)` in the SQL console (same in the Groovy console)

**Comment by ebocher** [comment]
Fixed thanks to @nicolas-f
