### ISSUE TITLE
Reorganize the two selection tools

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1339]
#### 1- Specifications 

* OrbisGIS version: 5.1-dev

#### 2- Expected behavior and actual behavior
I think it could be more clear if we could reorganize the two selection icons. By default, we should display only the "Select by intersection" icon. When keeping the click on this icon, we can choose the second one (select containing) (same behaviour as "Clear selection" or "Zoom to selection"

This issue is more or less linked to #1338 
@ebocher @SPalominos

**Comment by ebocher** [comment]
Good idea
