### ISSUE TITLE
Linux Ubuntu 18.04: Orbisgis needs at least a java 1.7+

### ISSUE THREAD

**Issue by OnkelTem** [orbisgis/orbisgis#1345]
#### 1- Specifications 

* OrbisGIS version: 5.1.0
* Java version: openjdk-11, openjdk-8
* Operating System: Linux Kubuntu 18.04

#### 2- Expected behavior and actual behavior
Running app

#### 3- Steps to reproduce the problem
Silly message saying that I don't fit requirement

```
$ sudo update-java-alternatives -l
java-1.11.0-openjdk-amd64      1101       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64
```

**Comment by OnkelTem** [comment]
I tried also to install JDK 7, but it doesn't exist for Ubuntu 18.04

**Comment by OnkelTem** [comment]
I switched system-wide java alternatives to use `java-1.8.0-openjdk-amd64` instead and it has been finnaly launched w/o the message. So it actually requires Java 1.7 _OR_ Java 1.8 which is not what the message requires: **1.7+**. 

How not to switch system whide java version to run just this application?

**Comment by nicolas-f** [comment]
Hi,

You can edit orbisgis.sh and replace java with /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java

Yes, there is currently no support for java9 -> java11

**Comment by SPalominos** [comment]
The error message has been updated and ask for java 7 or 8.

**Comment by OnkelTem** [comment]
> You can edit orbisgis.sh and replace java with /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java

Oh, it's so simple then :) Thank you.

> The error message has been updated and ask for java 7 or 8.

I confirm this. Thank you.
