### ISSUE TITLE
How to set CRS? (Projection cannot be changed)

### ISSUE THREAD

**Issue by OnkelTem** [orbisgis/orbisgis#1349]
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 1.8
* Operating System: Linux Kubuntu 18.04

#### 2- Expected behavior and actual behavior

I believe there should be some way to change/set projections of the layers/project and/or set CRS of a layer/project.

#### 3- Steps to reproduce the problem

1. I created a table with timezones (loaded from an shp file from here: https://github.com/evansiroky/timezone-boundary-builder) using a query like:

```
CALL FILE_TABLE('/path/to/combined-shapefile.shp', 'timezones');
```

2. Then I dragged the "Timezones" item from the GeoCatalog to Toc to get it displayed in the Map Editor pane.

3. It appeared there but without any CRS selected. Now if I add some WMS layer (e.g. OSM), I see that my timezones data is treated incorrectly, and displayed like a tiny dot somewhere in the sea near São Tomé and Príncipe :) I didn't find a way to to set CRS.

Also on the bottom bar of Map Editor there is section with text "**Projection: Unknown CRS**" and button which is seemingly responsible for changing CRS but it doesn't work.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
