### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jensrsf** [orbisgis/orbisgis#1355]
#### 1- Specifications 

* OrbisGIS version: 5.1.0-SNAPSHOT
* Java version: openjdk version "12.0.2" 2019-07-16
* Operating System: macOS 10.14.6 (18G95)

#### 2- Expected behavior and actual behavior

I use the command
$ mvn clean install
inside the orbisgis-master library.

Instead of completely installing, the following is output:

...
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/1.8.1/plexus-compiler-javac-1.8.1.jar (13 kB at 118 kB/s)
[INFO] Compiling 1 source file to /Users/jf/bin/orbisgis-master/api/framework-api/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: Source option 6 is no longer supported. Use 7 or later.
[ERROR] error: Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for platform 5.1.0-SNAPSHOT:
[INFO] 
[INFO] platform ........................................... SUCCESS [  1.425 s]
[INFO] Framework API ...................................... FAILURE [  4.603 s]
[INFO] log-file-writer .................................... SKIPPED
[INFO] framework .......................................... SKIPPED
[INFO] wkgui-api .......................................... SKIPPED
[INFO] commons ............................................ SKIPPED
[INFO] orbisgis-sif ....................................... SKIPPED
[INFO] core-jdbc .......................................... SKIPPED
[INFO] workspace-gui ...................................... SKIPPED
[INFO] postgis-jts ........................................ SKIPPED
[INFO] postgis-jts-osgi ................................... SKIPPED
[INFO] h2trigger .......................................... SKIPPED
[INFO] h2trigger-osgi ..................................... SKIPPED
[INFO] editor-jdbc ........................................ SKIPPED
[INFO] WMS-Client ......................................... SKIPPED
[INFO] core-map ........................................... SKIPPED
[INFO] core-export ........................................ SKIPPED
[INFO] sql-parser-api ..................................... SKIPPED
[INFO] sqlconsole-parser .................................. SKIPPED
[INFO] mainframe .......................................... SKIPPED
[INFO] docking-impl ....................................... SKIPPED
[INFO] progress-gui ....................................... SKIPPED
[INFO] Map Editor api ..................................... SKIPPED
[INFO] dbjobs ............................................. SKIPPED
[INFO] geocatalog ......................................... SKIPPED
[INFO] db-tree ............................................ SKIPPED
[INFO] toc-api ............................................ SKIPPED
[INFO] table-editor-api ................................... SKIPPED
[INFO] table-editor ....................................... SKIPPED
[INFO] SQL Console ........................................ SKIPPED
[INFO] logpanel ........................................... SKIPPED
[INFO] Map Editor ......................................... SKIPPED
[INFO] legend ............................................. SKIPPED
[INFO] toc ................................................ SKIPPED
[INFO] OrbisGIS OSGi Plugin Manager ....................... SKIPPED
[INFO] OSGi Plugin Manager GUI ............................ SKIPPED
[INFO] Toolbox ............................................ SKIPPED
[INFO] miglayout-osgi ..................................... SKIPPED
[INFO] rsyntax-osgi ....................................... SKIPPED
[INFO] rsyntax-language-support ........................... SKIPPED
[INFO] jts-core-osgi ...................................... SKIPPED
[INFO] jts-io-osgi ........................................ SKIPPED
[INFO] json-simple-osgi ................................... SKIPPED
[INFO] svg-salamander ..................................... SKIPPED
[INFO] itext-osgi ......................................... SKIPPED
[INFO] jai-osgi ........................................... SKIPPED
[INFO] orbisgis-dist ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:26 min
[INFO] Finished at: 2019-09-16T14:28:13+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project framework-api: Compilation failure: Compilation failure: 
[ERROR] error: Source option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :framework-api

#### 3- Steps to reproduce the problem

Download orbisgis from github, open Terminal and go to library 'orbisgis-master'. Type command: mvn clean install. (On my computer ;-)

**Comment by nicolas-f** [comment]
Hi,

The master branch is no longer maintained. 

You have to use the dev branch but its quite broken in the current state as it is not linked with up to date version of h2gis.

**Comment by jensrsf** [comment]
Thanks. My aim is to use the NoiseModelling plugin. But when I download the ready package https://github.com/Ifsttar/NoiseModelling/releases/download/2.1.2-SNAPSHOT/orbisgis-noisemodelling-2018-07-18.zip
and try to run it, it seems like my updated java version is not opened properly.

**Comment by nicolas-f** [comment]
Yes you will not be able to compile it with Java 11 either. So the only way is to find a Java 8 for your system.

**Comment by jensrsf** [comment]
OK, thank you.
