### ISSUE TITLE
Plugins Manager is empty after launch OrbisGIS

### ISSUE THREAD

**Issue by XinTian-student** [orbisgis/orbisgis#1357]
#### 1- Specifications 

* OrbisGIS version: 5.1.0 SNAPSHOTCN (2019-09-10)
* Java version: Oracle Version 8 Update 251
* Operating System: Windows 10

#### 2- Expected behavior and actual behavior

1. I want to use OSGi plugin, but I cannot add OSGi jar file into OrbisGIS. 

2. My plugins manager is empty after I launch OrbisGIS. The plugins that should be installed by default are not displayed in the plugin manager. As the picture is shown below: 
![Plugins manager](https://user-images.githubusercontent.com/59643945/81941798-935d9300-95f9-11ea-89c1-0b7699e62b0c.PNG)

Do you know why I don't have any plugins?

3. Every time I launch OrbisGIS I can only use the default workspace. If I change the workspace to another folder, the software will automatically quit. And every time when I launch the software, I have the following log in the terminal:
[log terminal.txt](https://github.com/orbisgis/orbisgis/files/4628860/log.terminal.txt)

4. When I start OrbisGIS, the software will automatically display Chinese. This situation may be due to the Chinese operating system. Is there any way to make the software display English? 

@nicolas-f @SPalominos @gpetit

**Comment by XinTian-student** [comment]
Every time I launch OrbisGIS I also got the following ERROR MESSAGES:
> Error accessing http://nexus.orbisgis.org/content/shadows/obr-snapshot/.meta/obr.xml
Error accessing http://plugins.orbisgis.org/.meta/obr.xml
当前工具无法启用

The third one is "The current tool cannot be enabled"

**Comment by XinTian-student** [comment]
Problems have been solved! It may because I download the wrong version.

**Comment by nicolas-f** [comment]
Hi,

Sorry for the delay.

I think the plugin system does not survive with the last server migration

@SPalominos obr plugin has been migrated ?

**Comment by XinTian-student** [comment]
Dear Sir/Madam, 

I am an MSc student working for my thesis now. My thesis is about describing and comparing the OGC SLD/SE standard with CartoCSS and Mapbox GL, then proposing the new extensions for the SLD/SE standard and implement the new extensions. Finally, giving the direction for future standardisation. In my thesis, I want to use OrbisGIS and OSGi bundles as the rendering engine to implement my new extensions. 

My proposal is using different style files to render one map. For example,  I wan to make a proportional symbol map to show the population of each province in The Netherlands, and I want to use the circle symbol to represent the number of population. The size of the circle symbol is proportional to the square root of the number of population.  Mapbox GL has a math function named sqrt(), and it allows the users to calculate the square root of the attribute values of the data. But the SLD/SE standard does not have this function. Therefore, I proposed an extension for the SLD/SE standards to add the sqrt() function into the SLD/SE standard. The specific way to implement the extension is described as follow.  

Step one: Creating two style file. The first one is written by the SLD/SE standard, and it includes all the parameters that define the map style, except for the parameters that set the symbol size. The second one is written by the Mapbox GL, and this file is encoded by JSON format. The second file is used to set the size of the symbol. 

Step two: Creating two OSGi bundles, the first one is used to parse the first style file, and the second bundle is used to parse the second style file. After that, two JAVA classes are generated and the second bundle as a package imported into the first bundle. 

Step three: Passing the parsed parameter values to the rendering engine to make a map. Do you think the method I proposed to implement the new extension is possible in OrbisGIS? 

Since I have not studied the JAVA language, I cannot program to verify my proposal. So I send my proposal to you and hope to get some suggestions or comments. If I have any unclear description, please let me know. I will try to describe my thoughts clearly. 

Have a nice day!! 

Kind regards,
Xin Tian

**Comment by ebocher** [comment]
I'm sorry about that but OrbisGIS UI  is no longer maintained.
We are working on a next generation of tools based on DBeaver.
If you want to test the SLD/SE feature type style function, please check https://github.com/orbisgis/orbismap
Thanks

**Comment by XinTian-student** [comment]
Thanks for your reply！This information is very useful for me!

Since my thesis is going to complete, it is hard to change the implement software and method at this stage. So, I would like to ask Can the old version of the OrbisGIS and OSGi bundles still be used to test the new extensions of the SLD/SE standard?

**Comment by nicolas-f** [comment]
Hi,

You said you didn't studied the Java language, so you didn't started to implement the software ?

Sorry but, although you can use OrbisGIS, we cannot offer you any help for this task as we have stopped its development.

**Comment by XinTian-student** [comment]
Hi,
I know how to launch the software, but I don't know how to use and add OSGi bundles in this software.
In my thesis, I didn't implement my extension, but I described the possible way to implement my extension. The way is that using OSGi bundles as the rendering engine. Because I read the article "A redesign of OGC symbology encoding standard for sharing cartography", So I hope the reference implementation method mentioned in this article can also be used in my thesis. 

For now, I just want to sure whether the old version of OrbisGIS can be used, and how to add OSGi bundles to the software?

If you cannot give any help with my question, it's also fine.

Thanks for your help!
