### ISSUE TITLE
Enhance Map Catalog API

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#138]
The Map Catalog API need to be more RESTful compliant.

Stick with https://github.com/irstv/orbisgis-server/wiki/MapCatalog-API-Reference

Plus
- Take description from the map context (with lang property)
- Ability to remove a remote map context
- User rights (view,add,edit) and authentication  

Remove apache HTTPComponents Client

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
