### ISSUE TITLE
Improve "insert row" in the table editor

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#317]
Currently, when you want to add a new row, you can click on the appropriate icon that @nicolas-f  just added few days ago.
When you click on this icon, a new panel (called "New row) appears, and shows all field that the user has to fill.
The idea is good in principle, but in fact it to complicated, especially when you have a lot of fields.

So what I propose is to simply create an empty line and to not use a specific panel. Then the user will manually change the values or execute an update instruction.

@ebocher

**Comment by ebocher** [comment]
Duplicate with askrow multiinputpanel scrollpane
