### ISSUE TITLE
Remove the edit toolbar when done editing layer

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#567]
When you start editing a layer in the TOC, a new toolbar appears --> OK.

Now, stop editing this layer --> the toolbar is still there. In my opinion, we should remove it from the UI.

@ebocher ?

**Comment by gpetit** [comment]
This issue needs Nicolas's improvement on edition tools.

**Comment by ebocher** [comment]
Done  ?

**Comment by gpetit** [comment]
Postpone to 5.2

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
