### ISSUE TITLE
Add a "table manager" to OrbisGIS

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#654]
It will be great if we could have a "table manager" in OrbisGIS.

In my mind, the "table manager" is a specific UI that allows user to manage the structure of each tables. In this interface, fields are listed and all their parameters are displayed. In a very simple way, we can change values (constraints, defaut value, PK, ...).
Moreover, we can change the order of fields (when one field is selected, green arrow icones allows to move up or down in the list).

Two icons allows to add new field or to remove existing one.

In the type field, user can change the value. If there is a conflict (i.e string value to integer), the interface display a message error.

Here is a virtual screenshot of what i'd like to have : 

![table_manager_2](https://cloud.githubusercontent.com/assets/1871248/2926652/49bc1e92-d75f-11e3-81d1-1f7ca3203b22.png)

So now, let's start the discussion... :-)

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
