### ISSUE TITLE
Message in the  output when save file

### ISSUE THREAD

**Issue by mlecoeuvre** [orbisgis/orbisgis#698]
Currently when you save a file you have no message in the  output. In the next version(orbisgis-dist-4.1.0-SNAPSHOT-2014-06-11) when you save a file you have `file saved` in the  output.

**Comment by gpetit** [comment]
@ebocher

**Comment by ebocher** [comment]
Use 
 
private static final Logger LOGGER = LoggerFactory.getLogger("gui."+ExportInFileOperation.class);

LOGGER.info(I18N.tr("The file "+ savedFile.getAbsolutePath()+ " has been saved."));

@nicolas-f  Is this correct ?

**Comment by nicolas-f** [comment]
almost ;)
```java
LOGGER.info(I18N.tr("The file {0} has been saved.", savedFile.getAbsolutePath()));
```

**Comment by ebocher** [comment]
yep ;-)
