### ISSUE TITLE
Pblm of current scale in the SE Rule panel

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#740]
I'm working with the V5.0.

In the style editor panel, you can specify some informations for the rule.
Here, you can determine the min / max scale of visibility. If you click on "Current", the scale is noted as "0" instead of the real scale.

See the screenshot attached.
![pblm_scale](https://cloud.githubusercontent.com/assets/1871248/4614594/b15b1b04-52e1-11e4-9f12-e9011807f1ec.png)

@ebocher

**Comment by SPalominos** [comment]
Resolved in PR Some fixes #937
