### ISSUE TITLE
Table not updated if pre-existing selection in the map

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#748]
In the map, select some geometries on layer A.
Then, open the table of layer A --> selected objects (in the map) are not highlighted in the table
--> so it seems that there is no link between map and table if the table is not already opened.

Now, do the same, but open the table before
--> open the table
--> select object in the map
--> objects are highlighted in the table

**Comment by gpetit** [comment]
Hop ...

**Comment by nicolas-f** [comment]
Has been fixed
