### ISSUE TITLE
Improve the Geocatalog with JTree

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#757]
It would be cool if we could improve the Geocatalog with a JTree.

Below is an illustration of what we could except.

![og](https://cloud.githubusercontent.com/assets/1871248/5246210/4270080c-7966-11e4-8fbd-06f014d5d2f6.png)

Database, Schemas, Tables, fields and constraints (keys, indexes, ...) are listed

**Comment by ebocher** [comment]
@gpetit  It's done...
