### ISSUE TITLE
Workspace folder with space issue on Windows and Linux

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#763]
If the workspace folder contain a space in windows one or more components cannot be loaded in this folder.

**Comment by ebocher** [comment]
@gpetit  Could u confirm ?

**Comment by ebocher** [comment]
@nicolas-f 
Could you confirm because you are now with WIN$ ;-)

**Comment by nicolas-f** [comment]
An error when trying to save a map with weird uri

```
 78279 [AWT-EventQueue-0] WARN  o.o.c.layerModel.AbstractLayer - Unable to create URI from Layer.Please fix the layer named BUILDINGS
```

**Comment by ebocher** [comment]
ouuu

**Comment by gpetit** [comment]
@nicolas-f where is the error in your example ? The layer BUILDINGS seems to be correct

**Comment by SPalominos** [comment]
This error is not only on windows, I have the same on using a workspace with space characters under linux (Ubuntu 14.04).
