### ISSUE TITLE
Use marlin-renderer for better performance ?

### ISSUE THREAD

**Issue by bourgesl** [orbisgis/orbisgis#769]
Hi,

I am the author of the marlin-renderer (OpenJDK pisces fork) that is already used by geoserver (extension) and gv sig CE:
https://github.com/bourgesl/marlin-renderer/

Latest release (0.4.5):
https://github.com/bourgesl/marlin-renderer/releases/tag/v0.4.5

I improved its performance to be equivalent to ductus (Oracle JDK) and several times faster than OpenJDK pisces:
https://github.com/bourgesl/marlin-renderer/wiki/Benchmarks

It is very easy to use (any JDK 6, 7, 8,9):
https://github.com/bourgesl/marlin-renderer/wiki/How-to-use

Hope it may be useful for orbis GIS,
Laurent Bourgès

**Comment by nicolas-f** [comment]
Hi,

Thank you for your interest in OrbisGIS. We follow your project for quite some time. We had not had time to test your library. We just tested without problems marlin-0.5.5.jar but we have a problem with missing class in marlin-0.5.5-sun-java2d.jar.

We did only one test for only a dataset with an average speed-up of 9% (data transfer included).

I think we will enable the optional use alternative rendering engines for drawing maps.
Our software architecture is based on OSGi. It seems that the manifest file required for this architecture is missing in your library.

We keep this open ticket until the plug-in is not developed.
-Nicolas Fortin

**Comment by ebocher** [comment]
@nicolas-f  you mean about 0.4.5 ?

**Comment by nicolas-f** [comment]
@ebocher yes sorry 0.4.5

**Comment by bourgesl** [comment]
Thanks for your interest !

Please note that multi-threaded rendering is possible with marlin : several views in parallel or several threads painting on the same image ...

Could you explain me what is the concrete problem in the OSGI context ?
Both jar files have a MANIFEST ... 

PS: As mentioned in the "How to use" page, it is not recommended to use the marlin-X.Y-sun-java2d.jar file for license issues:
"There is however a catch, according to the Oracle documentation using the "bootclasspath:p" option violates the Oracle binary license agreement, as such, the above should be used only for experimental purposes. The above applies to the Oracle JDK, at the time of writing it is not clear if it may apply to OpenJDK as well, or not."

Laurent

**Comment by bourgesl** [comment]
Nevermind

**Comment by bourgesl** [comment]
Hi,
After discussion with Erwan, it is time to try again using Marlin renderer in your startup script:
https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_3

Here is the shell script (extract) I use:
```
MARLIN_JAR_PREFIX=../lib/marlin-0.9.3-Unsafe

# Marlin renderer in lib folder:
BOOTCLASSPATH="-Xbootclasspath/a:$MARLIN_JAR_PREFIX.jar"

# Optional Marlin java2d patch in lib folder:
BOOTCLASSPATH="-Xbootclasspath/p:$MARLIN_JAR_PREFIX-sun-java2d.jar $BOOTCLASSPATH"

# Rendering engine:
RDR="org.marlin.pisces.DMarlinRenderingEngine"

JAVA_OPTS="-Dsun.java2d.renderer=$RDR $JAVA_OPTS"

java $BOOTCLASSPATH $JAVA_OPTS $JAVA_TUNING -cp $CLASSPATH <classname>
```

Here is the complete script (with all internal tuning options):
https://github.com/bourgesl/mapbench/blob/master/bin/env_marlin.sh

Laurent

**Comment by ebocher** [comment]
orbisgis.sh has been modified as follows

```
# Total memory in KB
totalMemKB=$(awk '/MemTotal:/ { print $2 }' /proc/meminfo)

MARLIN_JAR=marlin-0.9.3-Unsafe.jar

# If unable to retrieve the memory, run orbisgis with 1024M
if [ -z "$totalMemKB" ]; then
	cd $(dirname "$0")
	java -Xbootclasspath/a:$MARLIN_JAR -Dsun.java2d.renderer=org.marlin.pisces.DMarlinRenderingEngine -Xmx1024m -jar orbisgis.jar $*
# Else, uses a percentage of the physical memory
else
	# Percentage of memory to use for Java heap
	usagePercent=30

	let heapKB=$totalMemKB*$usagePercent/100
	let heapMB=$heapKB/1024
	cd $(dirname "$0")
	java -Xbootclasspath/a:$MARLIN_JAR -Dsun.java2d.renderer=org.marlin.pisces.DMarlinRenderingEngine -Xmx${heapMB}m -jar orbisgis.jar $*
fi
```
Just a naive test with the OrbisGIS UI
JDK8
10 manual rendering actions on a full extend

Case 1 :  Data is a linked shapefile to an H2GIS database that contains 480 000 polylines.
With Marlin
min : 18 s
max : 19 s

Without
min : 20 s
max : 23 s

Case 1 :  The shapefile has been imported to an H2GIS database.
With Marlin
min : 14 s
max : 15 s

Without
min : 14 s
max : 15 s

**Comment by bourgesl** [comment]
Marlin Renderer seems not giving any improvements, do you have anti-aliasing enabled ?
```
// Enable antialiasing:
graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
```

You can enable Marlin log to be sure it is working:
 -Dsun.java2d.renderer.log=true

Are you using Oracle JDK8 or OpenJDK8 ?

I suppose H2GIS results are better as spatial indexing helps clipping, that was explaining Marlin gains on shape files ?
Anyway it looks like a complex scene (480k polylines) so pixel blending may cost high (painting pixels).

Finally, it is possible to get Marlin internal stats (dumped by JVM ShutdownHook) with -Dsun.java2d.renderer.doStats=true (log must be enabled too).

**Comment by ebocher** [comment]
> Marlin Renderer seems not giving any improvements, do you have anti-aliasing enabled ?
> 
> ```
> // Enable antialiasing:
> graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
> ```
yes we have RenderingHints.VALUE_ANTIALIAS_ON 
> 
> You can enable Marlin log to be sure it is working:
> -Dsun.java2d.renderer.log=true
> 
> Are you using Oracle JDK8 or OpenJDK8 ?
OpenJDK8
> 
> I suppose H2GIS results are better as spatial indexing helps clipping, that was explaining Marlin gains on shape files ?
I think so
> Anyway it looks like a complex scene (480k polylines) so pixel blending may cost high (painting pixels).
> 
> Finally, it is possible to get Marlin internal stats (dumped by JVM ShutdownHook) with -Dsun.java2d.renderer.doStats=true (log must be enabled too).

Below some Marlin logs

```
INFO: ===============================================================================
INFO: Marlin software rasterizer           = ENABLED
INFO: Version                              = [marlin-0.9.3-Unsafe]
INFO: sun.java2d.renderer                  = org.marlin.pisces.MarlinRenderingEngine
INFO: sun.java2d.renderer.useThreadLocal   = true
INFO: sun.java2d.renderer.useRef           = soft
INFO: sun.java2d.renderer.edges            = 4096
INFO: sun.java2d.renderer.pixelWidth       = 4096
INFO: sun.java2d.renderer.pixelHeight      = 2176
INFO: sun.java2d.renderer.profile          = quality
INFO: sun.java2d.renderer.subPixel_log2_X  = 8
INFO: sun.java2d.renderer.subPixel_log2_Y  = 3
INFO: sun.java2d.renderer.tileSize_log2    = 6
INFO: sun.java2d.renderer.tileWidth_log2   = 7
INFO: sun.java2d.renderer.blockSize_log2   = 5
INFO: sun.java2d.renderer.forceRLE         = false
INFO: sun.java2d.renderer.forceNoRLE       = false
INFO: sun.java2d.renderer.useTileFlags     = true
INFO: sun.java2d.renderer.useTileFlags.useHeuristics = true
INFO: sun.java2d.renderer.rleMinWidth      = 64
INFO: sun.java2d.renderer.useSimplifier    = false
INFO: sun.java2d.renderer.usePathSimplifier= false
INFO: sun.java2d.renderer.pathSimplifier.pixTol = 0.125
INFO: sun.java2d.renderer.clip             = true
INFO: sun.java2d.renderer.clip.runtime.enable = false
INFO: sun.java2d.renderer.clip.subdivider  = true
INFO: sun.java2d.renderer.clip.subdivider.minLength = 100.0
INFO: sun.java2d.renderer.doStats          = true
INFO: sun.java2d.renderer.doMonitors       = false
INFO: sun.java2d.renderer.doChecks         = false
INFO: sun.java2d.renderer.useLogger        = false
INFO: sun.java2d.renderer.logCreateContext = false
INFO: sun.java2d.renderer.logUnsafeMalloc  = false
INFO: sun.java2d.renderer.curve_len_err    = 0.01
INFO: sun.java2d.renderer.cubic_dec_d2     = 1.0
INFO: sun.java2d.renderer.cubic_inc_d1     = 0.2
INFO: sun.java2d.renderer.quad_dec_d2      = 0.5
INFO: Renderer settings:
INFO: CUB_DEC_BND  = 256.0
INFO: CUB_INC_BND  = 51.2
INFO: QUAD_DEC_BND = 128.0
INFO: INITIAL_EDGES_CAPACITY               = 98304
INFO: INITIAL_CROSSING_COUNT               = 1024
INFO: ===============================================================================
INFO: ===============================================================================
INFO: Marlin software rasterizer           = ENABLED
INFO: Version                              = [marlin-0.9.3-Unsafe]
INFO: sun.java2d.renderer                  = org.marlin.pisces.DMarlinRenderingEngine
INFO: sun.java2d.renderer.useThreadLocal   = true
INFO: sun.java2d.renderer.useRef           = soft
INFO: sun.java2d.renderer.edges            = 4096
INFO: sun.java2d.renderer.pixelWidth       = 4096
INFO: sun.java2d.renderer.pixelHeight      = 2176
INFO: sun.java2d.renderer.profile          = quality
INFO: sun.java2d.renderer.subPixel_log2_X  = 8
INFO: sun.java2d.renderer.subPixel_log2_Y  = 3
INFO: sun.java2d.renderer.tileSize_log2    = 6
INFO: sun.java2d.renderer.tileWidth_log2   = 7
INFO: sun.java2d.renderer.blockSize_log2   = 5
INFO: sun.java2d.renderer.forceRLE         = false
INFO: sun.java2d.renderer.forceNoRLE       = false
INFO: sun.java2d.renderer.useTileFlags     = true
INFO: sun.java2d.renderer.useTileFlags.useHeuristics = true
INFO: sun.java2d.renderer.rleMinWidth      = 64
INFO: sun.java2d.renderer.useSimplifier    = false
INFO: sun.java2d.renderer.usePathSimplifier= false
INFO: sun.java2d.renderer.pathSimplifier.pixTol = 0.125
INFO: sun.java2d.renderer.clip             = true
INFO: sun.java2d.renderer.clip.runtime.enable = false
INFO: sun.java2d.renderer.clip.subdivider  = true
INFO: sun.java2d.renderer.clip.subdivider.minLength = 100.0
INFO: sun.java2d.renderer.doStats          = true
INFO: sun.java2d.renderer.doMonitors       = false
INFO: sun.java2d.renderer.doChecks         = false
INFO: sun.java2d.renderer.useLogger        = false
INFO: sun.java2d.renderer.logCreateContext = false
INFO: sun.java2d.renderer.logUnsafeMalloc  = false
INFO: sun.java2d.renderer.curve_len_err    = 0.01
INFO: sun.java2d.renderer.cubic_dec_d2     = 1.0
INFO: sun.java2d.renderer.cubic_inc_d1     = 0.2
INFO: sun.java2d.renderer.quad_dec_d2      = 0.5
INFO: Renderer settings:
INFO: CUB_DEC_BND  = 256.0
INFO: CUB_INC_BND  = 51.20000076293945
INFO: QUAD_DEC_BND = 128.0
INFO: INITIAL_EDGES_CAPACITY               = 98304
INFO: INITIAL_CROSSING_COUNT               = 1024
INFO: ===============================================================================

INFO: ArrayCache.BUCKETS        = 8
INFO: ArrayCache.MIN_ARRAY_SIZE = 4096
INFO: ArrayCache.MAX_ARRAY_SIZE = 16777216
INFO: ArrayCache.ARRAY_SIZES = [4096, 16384, 65536, 262144, 1048576, 4194304, 8388608, 16777216]
INFO: ArrayCache.THRESHOLD_ARRAY_SIZE = 16777216
INFO: ArrayCache.THRESHOLD_HUGE_ARRAY_SIZE = 50331648
```

**Comment by bourgesl** [comment]
It confirms Marlin is in action: good.
That also mean some tuning is possible: tile size & subpixel sampling...

Could you share marlin stats after running only 1 or few map renderings ?
Stats are only dumped at exit...

**Comment by ebocher** [comment]
Attached a dump for Marlin stats
[marlin_stats.txt](https://github.com/orbisgis/orbisgis/files/2792997/marlin_stats.txt)

**Comment by bourgesl** [comment]
Thanks,
It shows many ctx so orbisGIS is using a thread pool, you can minimize allocated context count by using 
-Dsun.java2d.renderer.useThreadLocal=true|false

See https://github.com/bourgesl/marlin-renderer/wiki/Tuning-options

It shows how to tune tile size and subpixels.
Anyway I will study your app with profilers (linux perf...) and find bottlenecks

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
