### ISSUE TITLE
Hide "Rendering" message in the output console

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#782]
In the V5.1, each time OG is drawing, you have a log message in the output console

```
Rendering done in 0,326 seconds
Rendering done in 0,077 seconds
Rendering done in 0,086 seconds
Rendering done in 0,063 seconds
Rendering done in 0,062 seconds
Rendering done in 0,126 seconds
Rendering done in 0,102 seconds
Rendering done in 0,087 seconds
Rendering done in 0,047 seconds
Rendering done in 0,045 seconds
```

We have to hide/remove this !

@ebocher

**Comment by nicolas-f** [comment]
I will add an option to show this message (hidden by default) using osgi configuration admin.

**Comment by gpetit** [comment]
@nicolas-f  any inputs ?

**Comment by gpetit** [comment]
@nicolas-f  can we disable this log as you suggested ?

**Comment by nicolas-f** [comment]
You don't want this message to be hidden by default ?

**Comment by gpetit** [comment]
Yes, but if I understand your PR, you will display if the rendering takes more than 1s ?

**Comment by nicolas-f** [comment]
I do two changes. First i change from Info log to debug log (so this message is not displayed anymore) and yes this debug message is displayed only if the rendering times takes more than 1sec and if OrbisGIS is configured to display debug message.

**Comment by gpetit** [comment]
Ok more clear for me ;-)
Seems perfect !

**Comment by SPalominos** [comment]
Issue resolved.
