### ISSUE TITLE
OG unable to reopen any workspaces because of index problem

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#793]
I was working with a workspace called "test" in which I had one linked shape files. To optimize my treatments, I added a spatial index on this layer.

This morning I downloaded the new OG snapshot ... and I'm not able to open any workspace. I have this error message

![capture du 2015-03-12 08 08 21](https://cloud.githubusercontent.com/assets/1871248/6615749/e0ad0bca-c8a6-11e4-88b8-a97298693493.png)

**Comment by ebocher** [comment]
@gpetit  please test it

**Comment by nicolas-f** [comment]
Has been fixed
