### ISSUE TITLE
expression ${parent.groupId} in pom.xml file

### ISSUE THREAD

**Issue by obonin** [orbisgis/orbisgis#797]
Maven 3.0 gives the following warning:

[WARNING] The expression ${parent.groupId} is deprecated. Please use ${project.parent.groupId} instead.
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

Not really important!
OB

**Comment by ebocher** [comment]
@nicolas-f  What do you think ?

**Comment by nicolas-f** [comment]
Just a find & replace in pom.xml..

**Comment by ebocher** [comment]
all pom must be updated ?

**Comment by nicolas-f** [comment]
yes. for the string ${project.parent.groupId}
