### ISSUE TITLE
Reactivate and Fix SQL syntax error higlighting

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#804]
SQL syntax error highlighting have been deactivated in the past due to performance problems. The goal is to do this things in breakable background process.

**Comment by ebocher** [comment]
It has been fixed ?
@nicolas-f

**Comment by nicolas-f** [comment]
It is still deactivated

**Comment by gpetit** [comment]
Who is responsible of this problem ? H2GIS or Rsyntax ?

**Comment by nicolas-f** [comment]
We use PrepareStatement with H2 in order to check if the syntax is correct. Such query take time and RSyntax evaluate the `parse` method into the swing thread. Then until H2 respond to the query, the user cannot type anything.

I think we have to found a way to run a background process and the next time  `parse` method is called, respond with the available h2 response.(if done)

**Comment by nicolas-f** [comment]
Done
