### ISSUE TITLE
Block selection for sql editor

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#807]
Selection by block of text instead of rows.

http://fifesoft.com/forum/viewtopic.php?f=10&t=303

**Comment by gpetit** [comment]
@nicolas-f can you explain a bit more ?

**Comment by nicolas-f** [comment]
More details here
https://en.wikipedia.org/wiki/Selection_%28user_interface%29#Column_selection

**Comment by gpetit** [comment]
Not sure to understand the value of this feature.
@nicolas-f can you explain why the block selection may be more useful comparing to line selection (in the SQL Console context)? Or else close this issue

**Comment by nicolas-f** [comment]
Its an additional feature, not replacing the default selection mode. The priority is trivial as a nice feature but not more.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
