### ISSUE TITLE
DB Tree - Tables with alphabetical order

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#816]
In the DB Tree, we should display tables using the alphabetical order

@nicolas-f

**Comment by nicolas-f** [comment]
Is it ok if all nodes in dbtree are in alphabetical orders too ?

**Comment by nicolas-f** [comment]
If it is ok then it is done here https://github.com/nicolas-f/orbisgis/tree/fix/dbtree_alpha_order

**Comment by ebocher** [comment]
Fine for me

**Comment by nicolas-f** [comment]
@gpetit don't want alphabetical order for columns

**Comment by nicolas-f** [comment]
I have to push some more changes

**Comment by ebocher** [comment]
@gpetit  please test it

**Comment by ebocher** [comment]
Great
