### ISSUE TITLE
Re-add the db connector UI in OG V5.1

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#819]
In the V5.1 we don't have any ways to connect to external (spatial) db.

For example, I start OG in the "H2GIS" mode and I would like to use PostGIS tables. Right now, it's not possible (no UI in the Geocatalog or errors with SQL).

When I execute the following query
```
CREATE LINKED TABLE IF NOT EXISTS toto ('org.orbisgis.postgis_jts_osgi.Driver', 'jdbc:postgresql://my_ip:5432/my_db','login','password','my_schema','toto');
```
I obtain this error message
```
Class "org.orbisgis.postgis_jts_osgi.Driver" not found; SQL statement:
CREATE LINKED TABLE IF NOT EXISTS toto ('org.orbisgis.postgis_jts_osgi.Driver', 'jdbc:postgresql://my_ip:5432/my_db','login','password','my_schema','toto') [90086-186]
```
Note that in the V4.0 we use to have a nice UI to connect to external db.

@nicolas-f @ebocher

**Comment by ebocher** [comment]
@gpetit 

ok to add the last DB UI.
What about the link table query, Is this fixed yet ?

**Comment by nicolas-f** [comment]
Hello,

Yes it has been fixed with last version of H2. It has been updated.

**Comment by nicolas-f** [comment]
UI has not been done

**Comment by ebocher** [comment]
duplicate with #917
