### ISSUE TITLE
DB Tree - indexes listed as tables

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#822]
In the DB Tree, if I'm connected to a postgis db, indexes (index, pk, fk, ...) are listed as tables.
We should remove them to be more clear.

See attached screenshot

![bug_db_tree](https://cloud.githubusercontent.com/assets/1871248/7767514/64a27c18-0073-11e5-8d40-63c27262e564.png)

@nicolas-f @ebocher

**Comment by nicolas-f** [comment]
Has been fixed
