### ISSUE TITLE
Fast rowset

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#828]
Find a way to optimise the use of the rowset object.

**Comment by nicolas-f** [comment]
Critical ? This is a blocking situation. You are not able to use OrbisGIS anymore..

**Comment by nicolas-f** [comment]
Ideas:

Store only batch's first PK and only when the batch are queried. (Fast init time)

The batch query is in the form (@thomasmueller advice)
```sql
SELECT * FROM MYTABLE WHERE PK > ? ORDER BY PK LIMIT BATCHSIZE
```
As PostGre is composed key, it may not work with ```tid``` type of PostGreSQL.

**Comment by nicolas-f** [comment]
```ctid``` column of Postgre can be used in conjunction with ```where ctid > ?``` however the order by consume time.

**Comment by nicolas-f** [comment]
It seems on PostgreSQL that unordered query are ordered by ctid (place on disk). We could reliably (disabling edition) for performance reason removing the ```order by ctid``` in this case.

**Comment by ebocher** [comment]
Sounds good. The order by will be re-activated during the edition mode.

**Comment by nicolas-f** [comment]
We assumed that a table without PK cannot be edited (as a row can move at each update).

**Comment by ebocher** [comment]
Ok.
@gpetit Could you confirm @nicolas-f proposal's ?

**Comment by nicolas-f** [comment]
Please note that with this new rowset the initialisation time will be removed however you will have an increased random access time.

**Comment by ebocher** [comment]
Perfect.

**Comment by ebocher** [comment]
Excellent
