### ISSUE TITLE
Accentuated characters problem in field values from imported shape file

### ISSUE THREAD

**Issue by sfaraut** [orbisgis/orbisgis#831]
It seems that OrbisGIS can't import properly several accentuated characters in field values from imported shape file.
For example, with "BAT_INDUSTRIEL" layer of IGN's BDTopo files (file BDT_2-1_SHP_LAMB93_D031-ED151/E_BATI/BATI_INDUSTRIEL.SHP), in the field "NATURE", the value "Bâtiment industriel" is converted to the lettre "B" only. 
![capture d ecran 2015-06-03 a 16 58 55](https://cloud.githubusercontent.com/assets/4488885/7964410/e88fea44-0a17-11e5-8c3f-a3ec30284ef7.png)

It is'nt a display glitch as this "B" field value is maintained as you export the layer as DBF database file.

Could be an encoding/decoding problem with "â" character, as I don't know how to configure charset in shape file import.

**Comment by ebocher** [comment]
Good catch @sfaraut. It's a bug. We will fix it asap.

**Comment by nicolas-f** [comment]
Hi,

This file does not provide the encoding in this header. Then the driver fallback to default international encoding "UTF-8". There is currently no gui for choosing encoding, you have to use SQL console to provide this information:

I have the same file, and found that it use windows fr encoding.

```sql
call shpread('/home/user/Data/BATI_INDUSTRIEL.SHP', 'BATI_INDUSTRIEL', 'cp1252');
```

**Comment by sfaraut** [comment]
Thanks Nicolas! It works that way!
>>There is currently no gui for choosing encoding, you have to use SQL console to provide this information
Will it be present in import file's dialog in some OrbisGIS future release? Or a warning in codepage/charset failing decoding process?

**Comment by sfaraut** [comment]
The problem of IGN's files concerns also their .DBF files. They seems to not contain codepage too!
It's really a shame!
But default codepage for DBF files should'nt be a windows encoding, maybe "iso-8859-1", or precisely "cp1252"?
In code source of "h2gis/DbaseFileHeader.java at master · orbisgis/h2gis" there is:

70:    public static String DEFAULT_ENCODING = "cp1252";
...
532:    // read Language driver
533:    byte lngDriver = in.get();
534:    String encoding = CODE_PAGE_ENCODING.get(lngDriver);
535:    if(encoding!=null && forceEncoding == null) {
536:        this.fileEncoding = encoding;
537:       }

But when there is no "Language driver" (codepage?) at all in that files,  it seems that the value of DEFAULT_ENCODING = "cp1252" is not taken in account...

Just my two cents...

**Comment by nicolas-f** [comment]
Yes you are right H2GIS read 0x00 in DBF header, then it fetch UTF-8. Default encoding is used if the CODE_PAGE_ENCODING does not contain the provided code. We use UTF-8 for code 0 as it is the most common case when reading dbf.

**Comment by nicolas-f** [comment]
We have to provide a GUI in OrbisGIS for each kind of file driver. This is in our todo list.

**Comment by ebocher** [comment]
This PR will be solved with  a groovy script available from OrbisToolBox.

**Comment by ebocher** [comment]
Solved with the toolbox import scripts
