### ISSUE TITLE
OrbisGIS file not found

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#838]
If a file cannot be found (has been deleted) OrbisGIS is not able to start.

g! 2015-06-24 11:09:38,371 ERROR [FileEngine.java:57] File not found:
/tmp/dataOSM.shp

**Comment by nicolas-f** [comment]
OrbisGIS is able to start with a missing ShapeFile. There is a unit test about that in H2GIS.
The full error message is:
```
2015-07-09 09:15:29,152 ERROR [FileEngine.java:58] File not found:
/home/fortin/Data/test dossier étrange/2014_CIMETIERE$.SHP
The table 2014_CIMETIERE$ will be empty. - o.h.d.f.FileEngine
```
