### ISSUE TITLE
Editing attributes without pk

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#849]
The button editing must be disable if the table does not contain any PK. So it will be not necessary to display the message  "Edition is disabled on table without single numeric primary key."

**Comment by ebocher** [comment]
Is it the same behaviour when the user wants to edit a layer  eg draw a geometry ?
@gpetit

**Comment by gpetit** [comment]
Ok to disable edition (both attributes and geometry) on a layer that has no PK.

But, for me, we should find a way to explain to the user why. So we need to display a message (when clicking on the edition icon (both for attributes and geometry))

**Comment by nicolas-f** [comment]
Yes. The message should be "For data safety edition is disabled when no primary key are available"

**Comment by ebocher** [comment]
Ok. I'm working on it.

**Comment by gpetit** [comment]
Perfect. May I just propose a very small improvement :-)

For data safety issues, edition is disabled when no primary key are available

**Comment by ebocher** [comment]
What about external file, eg shapefile.
A message ?

**Comment by nicolas-f** [comment]
We should check for read only using [ResultSet.GetMetadata][1] and inform the user. But OrbisGIS don't know that table is backed by a shape file.

[1]: http://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html#isReadOnly%28int%29

**Comment by ebocher** [comment]
But we can test the table type no ? 

If tabletype is external then no edition.

**Comment by nicolas-f** [comment]
It could be a temporary workaround. Checking for readOnly field is much more a viable solution for other cases (view, special table etc..)

**Comment by ebocher** [comment]
There is no difficulty to test this condition for the EditableSourceImpl because we can look at the table type when the table if open...  but it's a bit complex for LayerAction.
