### ISSUE TITLE
Remove column

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#850]
If you remove a column from the table editor, the content of table is not updated.

**Comment by ebocher** [comment]
and if the user clic on "refresh table content " an empty table appears

**Comment by ebocher** [comment]
any idea ?

**Comment by nicolas-f** [comment]
The update is triggered, however table structure change seem not to be handled correctly

**Comment by ebocher** [comment]
Are you ready to fix it ?

**Comment by SPalominos** [comment]
Issue linked to #986.

**Comment by ebocher** [comment]
If I remove a column I get the message

org.h2.jdbc.JdbcSQLException: Invalid value "6" for parameter "columnIndex" [90008-193]

**Comment by SPalominos** [comment]
I'm on it.

**Comment by ebocher** [comment]
Works well but the PR introduces minor bugs.

Execute in the SQL console
alter table USR add column test varchar;

->If the table editor is opened the new column doesn't appear
-> Click on the refresh button, the progress monitor (UI) is locked with the message "Update table state"  and it's not possible to kill it.

**Comment by SPalominos** [comment]
The PR should fix the problem.

**Comment by ebocher** [comment]
YES. A new small issue
Open the table editor 
Execute "alter table mytable add column test id" in the SQL console
The table is refreshed 
Clic on the new column in the header of the table editor, you will have the message

java.sql.SQLException: java.lang.IndexOutOfBoundsException: Column index 6 out of bound[1-5]

**Comment by ebocher** [comment]
+1
