### ISSUE TITLE
Add new row

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#852]
It will be nice to put the list of fields in JscrollPane.

The_geom field must be disabled as the pk field because the user will have in the future editing tools.

If I fill all field with the same value (for example sssss, sure it's stupid ), the OK button doesn't display any messages. A post validation on field type (numeric, text...) will be nice.

**Comment by nicolas-f** [comment]
I think we should not prevent user from typing the geometry wkt. It is more accurate than the editing tools.

**Comment by ebocher** [comment]
But the user can use the sql console to do that ?
@gpetit

**Comment by ebocher** [comment]
@gpetit  any point of view ?

@SPalominos  could please add a Jscrollpane to the AskValidRow MultiInputPanel in order to limit the size of the panel when there are too many of fields in table. 
This option will be interesting to create WPS panels on the fly.

**Comment by SPalominos** [comment]
@ebocher OK, I'm on it.

**Comment by ebocher** [comment]
thanks

**Comment by ebocher** [comment]
Jscrollpane added in https://github.com/ebocher/orbisgis/tree/somefixes

**Comment by SPalominos** [comment]
Resolved in PR Some fixes #937
