### ISSUE TITLE
Remove a row

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#853]
When a row is removed OrbisGIS throw "java.lang.NullPointerException".

**Comment by ebocher** [comment]
Note that the delete action works.

It would be nice to display the the SQL action in the panel as for create index action.

**Comment by nicolas-f** [comment]
The Gui is calling RowSet.deleteRow( ).  The underlying SQL is hidden.

**Comment by ebocher** [comment]
ok
