### ISSUE TITLE
WPS Example 2

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#865]
The idea is to build a script to compute a buffer.

Input data :  shapefile
Output data : shapefile

Parameters : 
Buffer distance :  double value (required)
quad_segs  : int (optional)

SQL  signatures of this function will be 

```mysql
GEOMETRY ST_Buffer(GEOMETRY geom, DOUBLE bufferSize);
GEOMETRY ST_Buffer(GEOMETRY geom, DOUBLE bufferSize,  INT quad_segs);
```

**Comment by SPalominos** [comment]
The example have been add to the ToolBox  with others.
