### ISSUE TITLE
Unable to edit a multipolygon layer

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#871]
I'm using the V5.1 from 09/09/15.

I want to test the edition tools.
So I extracted a part of the "COMMUNE" layer, made by IGN. (Select some objetcs and click on "create a datasource from selection".
Now I have a layer called "TEST" and I strat the edition --> In the "edition toolbar" only the "stop edition" icon is highlited. All the other ones are hidden.

Then I selected on object in the map. Here, I can just remove the mulitpolygon.

No possibilities to add, modify, ... geometries.

I made the same test on the "COMMUNE" layer (which was imported). Here the "add polygon" tool is available. When one object is selected, all the other icons are activ.

So the problem seems to be due to the created layer (here called TEST) ? Maybe a problem of metadata ?

@ebocher

**Comment by gpetit** [comment]
In the "GEOMETRY_COLUMNS" we can see that the "TYPE" is noted as "GEOMETRY".
So if there no constraint, we should be able to draw any kind of geometries.

**Comment by ebocher** [comment]
The create table select is not able to copy the geometry constraint. You must use alter table add.
A good way will be to change the create select table action to support constraint.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
