### ISSUE TITLE
Connect R with OrbisGIS

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#874]
It will be useful to connect R with OrbisGIS. There is an excellent project http://www.renjin.org/ that could help us to solve this issue.

**Comment by ebocher** [comment]
@gpetit ?

**Comment by nicolas-f** [comment]
It is already ready by using the PostGRE SQL DBI. https://github.com/hannesmuehleisen/renjin-dbi

**Comment by nicolas-f** [comment]
Sample here:
http://www.renjin.org/blog/2015-06-24-DBI-package-in-Renjin.html

**Comment by ebocher** [comment]
Yes.
What do you think about a R Console like SQL Console in OrbisGIS
It seems that Renjin has a scripting engine ?

```java

ScriptEngineManager manager = new ScriptEngineManager();
    // create a Renjin engine:
    ScriptEngine engine = manager.getEngineByName("Renjin");

```

**Comment by SPalominos** [comment]
Issue linked to  bedatadriven/renjin#121

**Comment by SPalominos** [comment]
The R-Conbsole plugin and the needed dependencies are plubished in OrbisGIS nexus. Still a problem : the `library(...)` command doesn't work. Work stills in progress.

**Comment by SPalominos** [comment]
The loading of the default packages has been fixed.
