### ISSUE TITLE
Groovy annotation ?

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#878]
The question is about the need of an annotation for each data type.

### Actual situation :
The **@GeoDataInput** and **@GeoDataOutput** for a script inputs and outputs allow the user to choose any spatial file he wants (*ShapeFile*, *GeoJSON*, ...) without any possibility of putting a constraint about the formats accepted (like just the *ShapeFile* are accepted as input).
The **@ShapeFileInput** and **@ShapeFileOutput** are used to specified that only shape files are accepted as input or output.

### The question :
Is there a need of an annotation for each format (**@ShapeFileInput**, **@GeoJSONInput**, ...) ?

#### Solution 1 :
Uses the GeoData annotation plus an annotation for each format.
- pro : easier and clearer for the user to constraint the accepted format.
- cons : more classes and more code. Need to add new classes for each new supported format.

#### Solution 2 :
Only uses the GeoData annotation an add a field to constraint the format (like *'extension = "shp" '*).
- pro : less code, less classes. No need to update the code if there is a new supported format.
- cons : Less clear for the user, more difficult for him to put a constraint.

What do you think @gpetit, @ebocher ?

**Comment by ebocher** [comment]
I vote for the solution2.
We can have a Geodata annotation without any constraints to support all formats and a list of suffixes (shp, geojson) to constraint the input and output,  eg extension = "shp, geojson" or extension = "shp".

**Comment by gpetit** [comment]
Ok for me too (solution 2) if we can have a format constraint

**Comment by SPalominos** [comment]
Ok!
