### ISSUE TITLE
LOG file

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#883]
For a end user (like me) it's quite hard to go to the system folder to display the content of the LOG file.
So I propose to show the log file in the configuration panel.

**Comment by nicolas-f** [comment]
Yes. We can also [more easily][1] add a ``help`` menu and a ``Show OrbisGIS log`` that will bring the log file content in the os editor.

[1]: http://stackoverflow.com/questions/6273221/open-a-text-file-in-the-default-text-editor-via-java

**Comment by ebocher** [comment]
No guarantee  to determine the default editor especially in a system-independent fashion.
So I propose to open a JDialog. This dialog will be also available in the workspace window as a button. 
Because sometimes (and I said sometimes) OrbisGIS crashes and it will be nice to display why ?

@gpetit  ?

**Comment by ebocher** [comment]
ready for a Jdialog with a textarea ?

**Comment by gpetit** [comment]
Postpone to 5.2

**Comment by SPalominos** [comment]
The best thing will be the following : on OrbisGIS crash, open a popup dialog which ask the user if he wants to send the crash report to the developpers. So the user won't have to search for the log file and to send it by hand.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
