### ISSUE TITLE
Bug when filtering values in the table editor

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#885]
I'm using the last V5.1 (build 2015/10/02).
In OG I imported a table "COMMUNE" from GeoFLA.
Then, in the table editor I'm trying to filter lines using the "select lines with the same values" tools --> on the field "NOM_REG" I obtain this error message 

```
Find field value with the following request:
SELECT "PK" FROM COMMUNE WHERE  "NOM_REG" = 'RHONE-ALPES'
Algo error
```

Then, I'm trying to do the same manually, in the search engine (at the bottom) (in "Find" or "SQL" mode), checking or uncheking options ... and I never obtain the appropriate result.

I also tried with numerci field ... and results are wrong
```
Find field value with the following request:
SELECT "PK" FROM COMMUNE WHERE  lower("POPULATION") LIKE '%138%'
```

@ebocher @nicolas-f any idea ?

**Comment by ebocher** [comment]
Could you please test with the sql console ?

**Comment by gpetit** [comment]
Yes it works when using the SQL Console

**Comment by ebocher** [comment]
fix
