### ISSUE TITLE
Zoom to selection icons are different

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#892]
"Zoom to selection" icons are different if you are in the TOC or in the attributes table.

We have to update in the attributes table in order to use the new one (which is used in the TOC)

@nicolas-f @ebocher

**Comment by nicolas-f** [comment]
You are talking about icons or button feature ?

**Comment by gpetit** [comment]
I'm talking about icons.
The behaviour is the same in both cases.
