### ISSUE TITLE
Background color improvements

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#899]
Now we have a Map configuration option that allows user to change the background color. Nice !

We just have to improve two things:
- the "Apply" button doesn't work
- the "Reset" button doesn't work

@ebocher

**Comment by gpetit** [comment]
And we should also add a valid default color (white)

**Comment by ebocher** [comment]
What it works on my laptop ?

**Comment by nicolas-f** [comment]
When he say it doesn't work he mean that it does not trigger a map editor refresh. About the default color, it is when he click on red cross.
