### ISSUE TITLE
 Display a progress monitor when the envelope is computed

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#909]
The first time, when the user drag from geocatalog to TOC a table it takes a long time to compute the layer extend, especially with H2GIS.

```sql
--- data is a table of 200000 polygons
select st_extent(the_geom) as env from data ; -> POSTGIS  =  0,2 s
select st_extent(the_geom) as env from data ; -> H2GIS =  > 2 s
```

**Comment by ebocher** [comment]
Is a difficult task ?

**Comment by nicolas-f** [comment]
Maybe trough this https://github.com/orbisgis/orbisgis/blob/master/bundles/h2trigger/src/main/java/org/orbisgis/h2triggers/H2Trigger.java#L60

**Comment by nicolas-f** [comment]
But impossible to know the current evaluated row for remote connections.

**Comment by ebocher** [comment]
But what about postgis ?

**Comment by ebocher** [comment]
Ok so  a null background will be nice.

**Comment by ebocher** [comment]
The idea is to display a progressmonitor on Layer getEnvelope()

**Comment by nicolas-f** [comment]
There is also a progress monitor when a source is dropped into the toc. The evaluation of GetEnvelope() is done under the label "Load the datasource dropped into the toc"

**Comment by ebocher** [comment]
But not when the envelope is computed.

**Comment by nicolas-f** [comment]
I'm sorry, but I don't understand
