### ISSUE TITLE
Enhance raster rendering

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#919]
When loading a layer use ST_Extrema on non RGB image and store it on layer (or store color model).

On rendering, use min-max of layer in order to compute the appropriate colormodel

**Comment by nicolas-f** [comment]
http://javadoc.orbisgis.org/jaistuff/code/display.DisplayDEM.html

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
