### ISSUE TITLE
New maven project for rendering test

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#923]
Creates a new maven project which run only the rendering from an .ows file and return informations about the rendering performance (running time ...).

**Comment by nicolas-f** [comment]
This project have to use the Renderer by providing the [CachedResultSetContainer][1]

 [1]: https://github.com/orbisgis/orbisgis/blob/master/bundles/map-editor/src/main/java/org/orbisgis/mapeditor/map/CachedResultSetContainer.java

**Comment by ebocher** [comment]
This project must able to test in batch mode several .ows files in order to evaluate various style configurations (AreaSymbolizer, Text, Point, Rules, Interpolate...).

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
