### ISSUE TITLE
Windows rendering issue

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#924]
There is a windows rendering issue. Rendered lines are converted into 2 points segments.

This uncommented sour line may be the cause.

https://github.com/orbisgis/orbisgis/commit/0582db0030c940c558325eb49cd0403a9b02e847#diff-77a5e2a176d571f4fec3f18f81c68392R429

**Comment by nicolas-f** [comment]
![og51](https://cloud.githubusercontent.com/assets/1382241/12455882/a9276daa-bf9d-11e5-8ede-091406d88fe6.png)

**Comment by ebocher** [comment]
I'm not able to reproduce this problem on Linux. 
I'll test on Win$

**Comment by nicolas-f** [comment]
This is only on rendering data using WGS84, decimation value goes wrong in this case. (wrong scale)

**Comment by ebocher** [comment]
Ok We must in the future manage and detect the map CRS to compute the appropriate scale.
