### ISSUE TITLE
Incremental tables with H2GIS database

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#934]
The last OrbisGIS release increments the table each time the workspace is reopened.

For example : 

New  workspace : one table named TOTO
Close and re-open =  two tables TOTO, TOTO_1
Close and re-open =  two tables TOTO, TOTO_1, TOTO_2

**Comment by nicolas-f** [comment]
The cause is the wrong recognition of Uri on table comments in the DataManager when opening a OWS file.

**Comment by nicolas-f** [comment]
I cannot fix this until Thursday..

**Comment by gpetit** [comment]
Thanks @nicolas-f for the diagnostic.
So it can be considered as a regression ?!
Perfect if you can solve this tomorow !

**Comment by nicolas-f** [comment]
Yes, it may have been caused by https://github.com/orbisgis/h2gis/pull/556 (not sure) This Pr change the stored uri format on table comments.

**Comment by nicolas-f** [comment]
Fixed

**Comment by ebocher** [comment]
Thanks
