### ISSUE TITLE
WPS drop table if the process fails

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#948]
The input file imported or linked must be dropped if the process fails.

**Comment by ebocher** [comment]
There is now an option on the WPS UI but it works only if the menu is checked before setting a URI.

**Comment by ebocher** [comment]
It seems there is a problem.
input data name from geocatalog :  toto 
operation :  buffer
input data name to geocatalog :  toto 

Returns an error an toto is dropped ....

**Comment by SPalominos** [comment]
It's "normal".
At the very start of the buffer process, it does a "_DROP TABLE IF EXISTS_" with the output table name.
The possible solutions can be :
- remove the "_DROP_" from the groovy script
- check on launching the process if an input and an output are the same
- During the process configuration, do not show the tables selected as input in the output fields

**Comment by ebocher** [comment]
Thks I vote to remove the DROP table in the script
