### ISSUE TITLE
Edition tools first geometry

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#950]
The first geometry field of a table is used as the default geometry for the edition tools. This is not correct because the Symbology Encoding standard used to display a table allows the user to specify its own geometry field (eg a table with two geometrie fields).
The OrbisGIS layer model must be adapted to return the index of the current geometry field and not the first one.

**Comment by gpetit** [comment]
Not clear for me.
In case you have two geometric fields, what do you want to do ? You want that OrbisGIS gives you the opportunity to choose which one will be displayed (because you are talking about SE) or edited ?

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
