### ISSUE TITLE
Export a map with proportional symbols

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#953]
When a map of proportional symbol of points is exported the size of the symbols does not match the size of the symbols set by the style to the mapContext.

**Comment by ebocher** [comment]
This bug appears only if the size of the image is modified by the user.

**Comment by SPalominos** [comment]
Postponed to 5.2 as it will be part of the new Renderer issue.

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
