### ISSUE TITLE
WPS last UI PostGIS

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#956]
The last WPS UI doesn't work with a PostGIS connection. The datasourceinput is null.

**Comment by ebocher** [comment]
Partially fixed because if the table name is ROUTE_db the script cannot display the geometry column named the_geom.

**Comment by SPalominos** [comment]
I can't reproduce the bug : I've created a table named "ROUTE_db" and when I open the process "Buffer", I can select the field "the_geom".

Does the problem appear with all the script (default and/or custom)? If not with which ?
In the DataStore, did you select the table from the "geocatalog" or from the "file" option ?
Does the other table work well ?

**Comment by ebocher** [comment]
Does the problem appear with all the script (default and/or custom)? If not with which ?
Default buffer script.
 In the DataStore, did you select the table from the "geocatalog" or from the "file" option ?
From geocatalog
Does the other table work well ?
yes

I will send to you a screenshot.

**Comment by ebocher** [comment]
Sorry it's a wrong table name "ROUTE_db"
