### ISSUE TITLE
Add action to open the toolbox

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#959]
The toolbox must be open : 

- with a right click  on a layer in the TOC,
- with a right click  on a table in the GeoCatalog,
- with  a icon from the table editor toolbar.

The toolbox must be filtered by a set of key words (tags). If any tags conditions are true then all the processes are displayed.

**Comment by ebocher** [comment]
The good way is to add this action menus in the WPS-client.

**Comment by SPalominos** [comment]
Issue linked to the #986.

@ebocher : As this issue is linked to a more complex one, maybe we should change/remove the milestone.

**Comment by ebocher** [comment]
yes
