### ISSUE TITLE
Find-Select toolbar on attribute table

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#962]
The action find or SQL on the table editor don't work. It returns "algo error" message.

**Comment by ebocher** [comment]
The SQL works well but the Find returns nothing.

**Comment by nicolas-f** [comment]
I have checked with latest build version and it seems to work.

**Comment by ebocher** [comment]
On a Postgis table

```java

Find field value with the following request:
SELECT "pk" FROM bati_indifferencie WHERE  lower("hauteur") LIKE '%9%'
ERREUR: la fonction lower(integer) n'existe pas
  Indice : Aucune fonction ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.
  Position : 44
```

**Comment by ebocher** [comment]
and this one returns nothing

```java

Find field value with the following request:
 lower("origin_bat") LIKE '%Autre%'
Find field value with the following request:
SELECT "pk" FROM bati_indifferencie WHERE  lower("origin_bat") LIKE '%Autre%'
```

**Comment by gpetit** [comment]
I tried with the last zip file (today) and the result is wrong because I have a shift of 1 line with the expected result (the selected line in the table is the following).

**Comment by ebocher** [comment]
Same pb with H2 database. I use the last build.

**Comment by ebocher** [comment]
Note : the sort column on the table editor is also broken.
Tested  with a postgis table and a flot8 datatype column.

**Comment by nicolas-f** [comment]
@gpetit What is the value of Bnd-LastModified in Plugin manager/table-editor ?

**Comment by gpetit** [comment]
@nicolas-f 

Bnd-LastModified : 19 janvier 2016 17:27:36 CET
Build-Jdk : 1.7.0_79
SymbolicName : org.orbisgis.table-editor
Public-Package : org.orbisgis.tablegui.api

**Comment by nicolas-f** [comment]
After each new minor or snapshot version change you have to run orbisgis_safemode first in order to use the new software components.

**Comment by gpetit** [comment]
Ouch ... works well now. Thanks @nicolas-f 
@ebocher could you confirm ?

**Comment by ebocher** [comment]
Thanks
