### ISSUE TITLE
Select rows in table editor

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#966]
The method to select a rows from table editor uses a temporary table.

```
String tempTableName = CreateTable.createIndexTempTable(connection, pm, selectedRows,"ROWID", INSERT_BATCH_SIZE);
```

What about if the user role on the database is read only ?

**Comment by ebocher** [comment]
Any input ?

**Comment by ebocher** [comment]
@nicolas-f ?

**Comment by nicolas-f** [comment]
It is used only when computing the envelope of selected rows.

 It should be reimplemented without requiring creating a temp table.

**Comment by ebocher** [comment]
Critical for 5.1
Because some people would have a read connection on a postgis db

**Comment by SPalominos** [comment]
For me it works, I can select rows in the TableEditor with a database on read only mode.
