### ISSUE TITLE
Improve DataFieldInput to link it with a fix table name

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#978]
Proposal

@DataFieldInput(
        title = "Identifier field",
        resume = "A field used as an identifier",
        dataStore = $schemaName$tableName)
String idField

the idField will be populated with the field names from $schemaName$tableName

**Comment by SPalominos** [comment]
Fixes but be careful, the dataStore value should be a String and the `'$'` should be escaped.
So it should looks like `dataStore = "\$schemaName\$tableName\$"`

**Comment by ebocher** [comment]
The tooltip must be update to schemaName.tableName and not $schemaName$tableName$

**Comment by ebocher** [comment]
```java
/** Name of the Geometric field of the DataStore inputDataStore. */
@DataFieldInput(
        title = "Geometric field",
        resume = "The geometric field of the data source",
        dataStore = "\$PUBLIC\$ROUTE\$",
        fieldTypes = ["GEOMETRY"])
String geometricField
```

is not able to populate the combobox with the geometry field.

Tested with a H2GIS database and a table named ROUTE

**Comment by SPalominos** [comment]
The fix will be merged at the same time as the #979 issue resolution.

**Comment by ebocher** [comment]
It will be cool to test also with a POSTGIS database

**Comment by SPalominos** [comment]
Tested with PostGIS and it works.

**Comment by ebocher** [comment]
clap clap
