### ISSUE TITLE
Improve FieldValueInput to link it with a table and a column names

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#979]
Proposal

@FieldValueInput(title="River name",
        resume="The river name",
        dataField = "riverNameField",
        dataStore=$schemaName$tableName,
        multiSelection = true)
String[] riverNameValue

**Comment by SPalominos** [comment]
After the fixes this is how it would looks like : 
```java
@FieldValueInput(title="River name",
resume="The river name",
dataField = "\$schemaName\$tableName\$riverNameField\$",
multiSelection = true)
String[] riverNameValue
```

**Comment by ebocher** [comment]
Perfect

**Comment by ebocher** [comment]
Second clap clap ;-)
