### ISSUE TITLE
Sort column with a postgist table

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#981]
The sort action from the table editor is wrong with a postgis table.

**Comment by ebocher** [comment]
Thanks a lot

**Comment by nicolas-f** [comment]
Please revert this pull request has it breaks sort feature.

We do not return primary key in this function but row number. This is why I write this unit test. JTable RowModel is handling row id (0-n) not primary keys.

**Comment by SPalominos** [comment]
Ok, but we need a fix on that issue. 
Before reverting this PR, do you have any fix to propose ?

**Comment by nicolas-f** [comment]
I have to install PostGRE in order to test it. Have you found the issue with PostGRE ?

**Comment by ebocher** [comment]
In the title ;-)

**Comment by nicolas-f** [comment]
But why is it wrong with PostGre and not with H2.

**Comment by SPalominos** [comment]
The problem appears with postgres only.
The problem is that in ReadTable, when you get the columnValues (the row id list) in
```java
while(rs.next()) {
     columnValues.add(pkValueToRowId.get(rs.getLong(1)));
     sortProgress.endTask();
}
```
, with H2 the rowId is equals to the PrimaryKey. But with postgres, the rowId and the PK are different.

**Comment by nicolas-f** [comment]
Yes the rowid and the pk may be different with H2 too. Primary key is unique, rowid is unique but also must be in the range 1-n incremental.

I think we have to provide the JTable RowSet to this function in order to have to good default ordering of rows.

**Comment by SPalominos** [comment]
Nice, so are you ready to fix it ?
If yes, i'll revert the PR.

**Comment by SPalominos** [comment]
I did a fix with what you said on this commit 6c79501 . Was it why you thought about ?
It works well but the only problem is that sort is very very slow.

**Comment by nicolas-f** [comment]
The fix is here https://github.com/orbisgis/orbisgis/pull/992
The sort can be speed up if we create an index on the column.

**Comment by ebocher** [comment]
Create an index on each column is not a good way. We must in the future find a better approach.

**Comment by SPalominos** [comment]
Postponed to 5.2

**Comment by ebocher** [comment]
Fixed excellent
