### ISSUE TITLE
Convert OrbisGIS actions into wps processes

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#986]
Actually the OrbisGIS actions (remove row, import file, create index ...) are written in Java, sometimes calling SQL. But those action could also be written into wps process (Groovy).
The idea will be to replace the Java code by a call to a wps process for each action.

This will have several consequences :
- If a script is not present in the wps-service, the action become unavailable. So it become possible to manage the list of tools accessible by the user. It is also possible to create an OrbisGIS version dedicated to one specific use.
- The actions will be placed in separated bundle. Once the bundle is loaded in the plugin manager, the action become available. For example, the 'table-editor' bundle will have a 'table-editor-actions' bundle which contains the 'AddRow' and 'RemoveRow' actions. If the action bundle isn't loaded, the action are unavailable.

**Comment by ebocher** [comment]
This idea must be extended to the toolbox. Indeed, a developer must be able to populate with a plugin the toolbox tree with its own scripts.
