### ISSUE TITLE
Error with the projections

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#988]
Issue get by @gpetit with the the following SQL script (simplified). OrbisGIS has a strange behavior : 

``` sql
DROP TABLE IF EXISTS FRANCE_L93, FRANCE_L2E;
--Save the union of all the geometries of the table COMMUNE in FRANCE_L93
CREATE TABLE FRANCE_L93 AS SELECT ST_UNION(ST_ACCUM(THE_GEOM)) as THE_GEOM FROM COMMUNE;
--Set the SRID to L93
UPDATE FRANCE_L93 SET THE_GEOM = ST_SETSRID(THE_GEOM, 2154);
--Create the table FRANCE_L2E wich is the same as FRANCE_L93 but with the SRID L2E
CREATE TABLE FRANCE_L2E AS SELECT ST_TRANSFORM(THE_GEOM, 27582) as THE_GEOM FROM FRANCE_L93;
```

If you places `FRANCE_L93` and `FRANCE_L2E` in the TOC to draw them, and then does a right click on `FRANCE_L2E` -> `Zoom to`, the map-editor zoom to the `FRANCE_L93` layer!
Whereas the layer `FRANCE_L2E` is well drawn and the geometry of both tables are good.
But the drawing in the map-editor disappears when the drawing of the layer `FRANCE_L93` become invisible.

But if you does a `SHPWrite` and then a `SHPRead`, to reload the table, everything works.

And if you try to do an intersection with the `FRANCE_L2E`, it seems to use the  `FRANCE_L93` envelop.

**Comment by ebocher** [comment]
So the problem seems linked to OrbisGIS ?

**Comment by SPalominos** [comment]
Yes, maybe it is because the envelop is kept in cache.

**Comment by ebocher** [comment]
yes on Layer you have 

```java
Envelope cachedEnvelope = envelope;
        if (cachedEnvelope.isNull()) {
```

**Comment by ebocher** [comment]
@gpetit 
Are you able to test with a postgis database ?

**Comment by ebocher** [comment]
@gpetit ?

**Comment by ebocher** [comment]
@gpetit ?

**Comment by gpetit** [comment]
I just tested on OG - PostGIS mode and it seems to work well. No problem to display both layers and to zoom on it.

**Comment by gpetit** [comment]
We made a test, with this instruction (executed in the OG SQL Consol) : SET CACHE_SIZE 0
... and it works. The zoom to FRANCE_L2E layer works well.

**Comment by ebocher** [comment]
So a bug must be reported to H2 team.

**Comment by gpetit** [comment]
@SPalominos I'm not able to explain very clearly this issue to H2 Team. Could you contact them ?

**Comment by SPalominos** [comment]
The problem comes from H2GIS `ST_Transform` method. When a clone is done, the envelope isn't reset. Issue transferred to orbisgis/h2gis#869

**Comment by ebocher** [comment]
Very good catch
