### ISSUE TITLE
OrbisGIS .deb, .exe and APT repository

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#989]
To make the update of OrbisGIS easier for users, an APT repository will be great. Some information about its creation can be found here : [HowToSetupADebianRepository](https://wiki.debian.org/HowToSetupADebianRepository#APT_Archive_Types).

The OrbisGIS website actually provides a `.zip` file but we could also add a `.deb` (debian package) and a `.exe` (windows executable).

**Comment by ebocher** [comment]
It will nice to have  

deb http://orbisgis.org/debian unstable main

**Comment by SPalominos** [comment]
A quite complete tutorial : https://doc.ubuntu-fr.org/tutoriel/creer_et_administrer_un_ppa_sur_launchpad

**Comment by ebocher** [comment]
A Ubuntu DEB repository is now available. A link must be added on the OrbisGIS web site @gpetit

**Comment by SPalominos** [comment]
It will also be great to add an help option to the orbisgis command and a man page.

**Comment by ebocher** [comment]
@gpetit 
Could you please add an image or some more sexy info about the ppa on the OrbisGIS website

**Comment by gpetit** [comment]
I think we can close this issue. Thx @SPalominos for the PPA
