### ISSUE TITLE
WPS client small issues

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#995]
- [x] trim space on tag list.  keywords = "Vector,Geometry,Properties" and keywords = "Vector, Geometry,Properties" returns two times the tag Geometry in the jtree.
- [x] add tooltip  on LiteralDataInput Boolean
- [x] add tooltip  on the paste button
- [x] rename inputs and outputs by input(s) and output(s)
- [x] on script rename defaultValues propertie by selectedValues

**Comment by ebocher** [comment]
[ ] expose to the WPS script the JDBCUtilities method hasTable ?, hasField...

**Comment by ebocher** [comment]
- [ ] add a metadata information to set if the wps script is supported by postgis or h2gis

**Comment by SPalominos** [comment]
Issue solved in the branch dev/wps.
